### ISSUE TITLE
Incidence Rates: suggestion to add warning when time at risk has zero days

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Atlas#1008]
### Expected behavior
I am helped by the tool.

### Actual behavior
It runs the analysis even though it does not make sense to do so.

**Comment by pbr6cornell** [comment]
@PRijnbeek may win the award for snarkiest issue post here.

Some basic error handling would be useful, to make sure that time-at-risk start <= time-at-risk end.  But, I'll note, that if time-at-risk  = START+0d  --> START +0d,  that is still a valid time-at-risk, basically it means you are looking for events that occur on the index date.    We could ask the user: 'did you intend to specify the time-at-risk as only the index date?', since that's probably an unlikely scenario and more likely to be an error where the user forget to change the time-at-risk end.

**Comment by chrisknoll** [comment]
I'm sorry if this is the wrong behavior, but the IR analysis will ignore any outcomes that happen on the time at risk start date. (ie: outcomes msut be after the time at risk start). The reason for this is that if you calculate the 'rate per person years' of an event that happens on a start date, the calculation will be 1 case / 0 time, which is divide by zero.  So, we only look for outcomes after the TAR start.  Again, I apologize if this is the wrong behavior, it just seems the reasonable thing to do.
