### ISSUE TITLE
Clear filter on a new vocab search

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Atlas#103]
Hi all,

Filters remain in place after searching for a completely new vocabulary term, which can result in showing 0 results as that filter term may not be related to the new vocab search term.

Could we clear the filter box on any new vocab search?

Thanks,

Ajit

**Comment by anthonysena** [comment]
To clarify a detail: the facet search is reset properly but the text filter above the table does not clear after each search attempt. To reproduce, search for a term, use the text filter above the results to filter and then perform another search. The text filter will remain intact instead of being reset.

**Comment by anthonysena** [comment]
In V2.0 of Atlas, the search will reset each time which will prevent this bug.
