### ISSUE TITLE
Error in 'included concepts' and 'included source codes' queries used in ConceptSetExpressions

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Atlas#104]
If you try to create a 'non-standard' conceptset expression, by selecting a concept (and its descendants) and then excluding other non-standard concepts (with or without their descendants), you will see that the non-standard concepts that you tried to exclude still appear on the 'included concepts' and 'included source codes' tabs.  We need to make sure the exclusions get applied to both standard and non-standard concepts.

**Comment by chrisknoll** [comment]
I'll take this one up. This is very interesting because the mechanics behind the concept set expression is to start with everything that is include,d left join to everythign you want excluded, and then return everything where the left join is null (ie: everything not found in the exclusion list).  I need to see what the raw query is executing.
