### ISSUE TITLE
IRs comparison view

### ISSUE THREAD

**Issue by pavgra** [OHDSI/Atlas#1041]
Today IR results page allows seeing results for a single target / outcome cohort pair at a time w/o being able to compare results across different pairs. During the DC Symposium there was a nice slide (presented by @cgreich) for IRs display:

![image](https://user-images.githubusercontent.com/10010071/47191923-f56bee80-d317-11e8-8374-639260c08591.png)

Would be great to have such view in Atlas.

**Comment by anthonysena** [comment]
Linking to a related issue here: OHDSI/WebAPI#366

**Comment by pbr6cornell** [comment]
So, first my methodological objection:  we deliberately have made Incidence report its statistics on a 'per target' basis, because putting two target cohorts side-by-side, as shown here naturally leads to readers drawing unadjusted comparisons and potentially making faulty inferences.  If someone wants to make a valid comparison between two exposure cohorts, they should consider a population-level effect estimation study (which will provide this format of a descriptive summary table, but it will also be accompanied with the appropriate statistical comparisons).

I don't have an objection to showing multiple outcomes 'per target' (as shown here by the rows), though one has to be careful to use the data only as a descriptive analysis of clinical characterization, and not draw any inferences.

With all that said, I think ATLAS 3.0 provides us a good opportunity to revisit our general reporting framework.  Currently, we display data One Source / One Target / One Outcome at a time, but there are valid needs to present multiple results across sources/targets/outcomes and we need to decide how to handle that responsibly.

**Comment by cgreich** [comment]
Should we think of some warning text if people display more than on incidence next to each other? Something like "Consider population-level estimation"?

**Comment by anthonysena** [comment]
Closing due to age.
