### ISSUE TITLE
error while browsing record count tab

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Atlas#1064]
### Actual behavior
![image](https://user-images.githubusercontent.com/6586384/47508720-9f7cd680-d842-11e8-8b6a-ecc868ce941e.png)

### Steps to reproduce behavior
Browse to concept (https://epi.jnj.com/atlas/#/concept/45888235)
Switch to record count tab

**Comment by aklochkova** [comment]
@fdefalco Could you please specify conditions led to the error? I can open this concept without issues. 
![image](https://user-images.githubusercontent.com/38942654/47509679-41221900-d87f-11e8-895f-d400dc45b7c9.png) 
![image](https://user-images.githubusercontent.com/38942654/47509699-497a5400-d87f-11e8-8d6a-0ebfd873e604.png)

**Comment by fdefalco** [comment]
In our environment no special conditions are required. Load the page, switch to the tab, error is thrown.

**Comment by pavgra** [comment]
@fdefalco , could you provide some debugging info - e.g. at which line the thing happens? I am confused since I don't see a place where a record count API could be called without source key in the path. The url should be `url: config.webAPIRoot + 'cdmresults/' + sourceKey + '/conceptRecordCount',` while at your screenshot it is just `url: config.webAPIRoot + '/conceptRecordCount'`

**Comment by fdefalco** [comment]
@pavgra It happens here:

https://github.com/OHDSI/Atlas/blob/master/js/pages/concept-sets/concept-manager.js#L351

If any failure occurs inside that for loop then the application stops running. In this case it appears we have a configuration error in our environment that causes one of the sources to fail.  We are going to fix our configuration error, but it would be helpful to have this fail gracefully in the case that a record count request fails for some reason.
