### ISSUE TITLE
UI improvements for CC

### ISSUE THREAD

**Issue by pavgra** [OHDSI/Atlas#1078]
1. Add facets to filter by Domain in Feature analyses list and Feature analyses popup
1. Allow picking multiple Feature Analyses from Feature analyses popup inside CC page (inc. select all filtered)
1. Add filtering by analysis domain into CC results page
1. Return back "Explore" button for concepts presented in CC results (like it was before in Generate w/ features)
![image](https://user-images.githubusercontent.com/10010071/47681662-76d94180-dba0-11e8-8af5-e74f6433c73a.png)

@chrisknoll , I remember we had some more (not speaking here about Generations tab) but was not able to find the comment which you or @pbr6cornell posted after our call

**Comment by chrisknoll** [comment]
When either a feature or characterization project is open, the left nav does not indicate an 'open' project (green indicator) or if something in the nav is dirty (red indicator).

By clicking on the left nav, it should take you to the open project (if there is something open).

However, unlike all the other navs, you could have 2 different things open at the same time under cohort characterization. So, recommend you always have 2 tabs beneath the characterization nav, and beneath each tab, you have either the 'open' design, or the design list (either characterization or feature).  You may want to store the 'state' of the active tab so that when you click on the left nav, it returns to the last 'selected' tab that the user selected (the left nav's URL will be dynamic, based on the last 'active tab' so clicking on the left nav will direct you to the route of the selected sub-tab).

Hope that makes sense, if there was some other behavior you prefer, I'm happy to review it with you.

**Comment by pavgra** [comment]
@wivern , address missed margins pls
![image](https://user-images.githubusercontent.com/10010071/47790349-4f43bf80-dced-11e8-9b5d-20768a702c26.png)

**Comment by pavgra** [comment]
@wivern , recently there were updates to dirtyFlag caused by performance issues. From now, the flag is reacting to observables changes only. Thefeore, we need to update handling of design and make it similar to Pathways approach. Currently, it is impossible to create new / update design - button is always disabled.

**Comment by pavgra** [comment]
@wivern , 

1. Why does this screen

- Show each line 2 times?
- Do not allow to differentiate between cohorts? - I would even propose to show only 1 cohort per popup or at least introduce selector and additional column / caption

![image](https://user-images.githubusercontent.com/10010071/48574744-f4f65180-e8dd-11e8-8cff-f27db3f2fa68.png)

2. Doesn't seem that anything is happening:

![cc-explore](https://user-images.githubusercontent.com/10010071/48574941-8b2a7780-e8de-11e8-8e80-0c1026fefc9e.gif)

**Comment by pavgra** [comment]
@wivern ,

Explore results are still duplicated:
![image](https://user-images.githubusercontent.com/10010071/48863850-ca524000-ed98-11e8-9d43-1030d57fce49.png)

And there is still no way to differentiate between two cohorts:
![image](https://user-images.githubusercontent.com/10010071/48863872-dfc76a00-ed98-11e8-9e48-e80a2da6c37b.png)

Also, could you give an example of Explore button being active? And any relationship types other than "selected"?

**Comment by wivern** [comment]
There are examples of ancestor and descendant relationship types below:
![explore_cc](https://user-images.githubusercontent.com/1109753/48891657-03e48300-ee4d-11e8-9b99-32e94e516b53.png)
![explore_cc2](https://user-images.githubusercontent.com/1109753/48891665-0ba42780-ee4d-11e8-876f-e46d85fca62c.png)
