### ISSUE TITLE
Presort characterization table results to display highest to lowest %

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#1127]
### Request
When the characterization tables display they are sorted alphabetically by concept name. It would be more intuitive to have the default be sorting by highest to lowest % for each analysis generated.

**Comment by johnSamilin** [comment]
@jhardin29 which column exactly should be used to sort characterization results?

**Comment by pavgra** [comment]
This is related to Prevalence analyses which do have "Pct" column. In case of single cohort mode there is one such column - so we sort by it. In case of comparison mode, there are 2 cols, one for each cohort, so I suggest to sort by "Pct" column related to the first cohort.

**Comment by chrisknoll** [comment]
Or alternatively, sort by the 'stdDiff' column because when looking at a cohort comparison, you are looking for those covariates which show the largest standardized difference.

Note: don't know if the behavior works this way, but when sorting the stdDiff column, the value used to sort should be ABS(stdDiff) because -6.5 and 6.4 have similar magnitudes, just in one case it is towards choort 1 and the other it's towards cohort 2. But, we would want to see the order of standard diff be sorted like 9.8 -8.7, -8.4, 6.5, -5.4...etc.   and not 9.8, 6.5, -5.4, -8.4, -8.7.  Just calling this out in case it's something you can change while adjusting the default sort order in this issue.

**Comment by pavgra** [comment]
> don't know if the behavior works this way, but

it works this way...

**Comment by chrisknoll** [comment]
Excellent, then I'd recommend that when doing cohort comparison, sort on StdDiff column (descending) by default.

**Comment by pavgra** [comment]
Makes sense. @johnSamilin , please address the suggestion

**Comment by johnSamilin** [comment]
Ok, and what about distribution reports?

**Comment by chrisknoll** [comment]
I'd sort by median.  Sorry for the delay in response, this PR got buried.
