### ISSUE TITLE
Data sources drug report doesn't show ingredient level for drugs

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#1140]
### Expected behavior
go to a datasource, drug report, type in filter box a drug name, for example, levothyroxine, ingredient level should be included with the formulations
### Actual behavior
go to a datasource, drug report, type in filter box a drug name, for example, levothyroxine, only the formulations show
### Steps to reproduce behavior
go to a datasource, drug report, type in filter box a drug name, for example, levothyroxine and no ingredient level information is displayed

![image](https://user-images.githubusercontent.com/11822115/48641600-4c60f400-e9a8-11e8-97d0-a8c218f78a32.png)

**Comment by fdefalco** [comment]
After discussing with @jhardin29 determined that the confusion comes that this is called the 'Drug' report instead of Drug Exposure.  Since we're summarizing Drug Exposure we don't see ingredient level information, which is summarized on the Drug Era report. I've update the report names to make it more clear what is in the report.

**Comment by chrisknoll** [comment]
Closed by #1165.

**Comment by pavgra** [comment]
@chrisknoll , how is it closed by #1165? There is separate https://github.com/OHDSI/Atlas/pull/1167 by @mpozhidaeva for the issue

**Comment by chrisknoll** [comment]
There was a commit message in the PR that was squashed to close this, so I assumed it was closed.  If you find any others, please re-open.

**Comment by anthonysena** [comment]
Closing since #1167 was merged into master.
