### ISSUE TITLE
Existing characterization - cannot remove cohorts to compare - page crashes

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#1154]
### Expected behavior
Go to existing characterization #58/results/112553 - attempt to remove cohorts from comparison, cohorts are removed

### Actual behavior
Go to existing characterization #58/results/112553 - attempt to remove cohorts from comparison, page crashes

### Steps to reproduce behavior
Go to existing characterization #58/results/112553 - attempt to remove cohorts from comparison

**Comment by johnSamilin** [comment]
@jhardin29 is it still reproducable?

**Comment by anthonysena** [comment]
Hi @johnSamilin - we're still running v2.6.0 from the tag in our environment so I'm guessing that it will still be reproducable for @jhardin29. If you feel this is addressed with newer code that is on the master branch, let me know and we can update our environment to see if the issue is resolved. Thanks!

**Comment by johnSamilin** [comment]
duplicates #1142

**Comment by anthonysena** [comment]
This will be addressed as part of work for #1142 and we'll close out this issue.
