### ISSUE TITLE
Readme file of ATLAS generated PLE package should recommend to use CohortMethod v3.0.2 not v3.0.1

### ISSUE THREAD

**Issue by chandryou** [OHDSI/Atlas#1221]
### Expected behavior
Currently, ReadMe file of PLE package generated by ATLAS suggest to use CohortMethod v3.0.1
CohortMethod v3.0.1 has an error which was solved by this [thread](https://github.com/OHDSI/CohortMethod/issues/72).

### Actual behavior

Readme file of ATLAS generated PLE package should recommend to use CohortMethod v3.0.2

**Comment by anthonysena** [comment]
Tagging @schuemie on this since it will require an update to Hydra and would want some feedback on this proposed plan of attack:

- Update the `README.md` and `DESCRIPTION` files in `Hydra/inst/skeletons/ComparativeEffectStudy_v0.0.1.zip` to reference `ohdsi/CohortMethod >= 3.02`
- Update WebAPI to use v0.0.3-SNAPSHOT of Hydra to pick up this change

Assuming that works, we'd create a release tag on Hydra for v0.0.3 once Atlas/WebAPI 2.7.0 are ready.

**Comment by schuemie** [comment]
I've updated the readme, [and updated the other dependency versions as well](https://github.com/OHDSI/SkeletonComparativeEffectStudy/commit/c60701d735934c7e2d53f7cf6864f945a3c90d23#diff-0e9eeace9b0166e33f79ccc6b694a708R27). Let me know if this is ok, and I'll bake a new Hydra. 

We're currently at Hydra v0.0.3. Do you want me to increase the version number to v0.0.4?

**Comment by anthonysena** [comment]
@schuemie thanks for that - let's keep Hydra at v0.0.3 and we'll update the reference in WebAPI to use that version of the library. Thanks!
