### ISSUE TITLE
Multiple copies of each item

### ISSUE THREAD

**Issue by hripcsa** [OHDSI/Atlas#126]
Under cohorts->cohort->reporting, I see multiple items in each view, such as each disease being repeated multiple times in a report, or even male-male-female-female being reported under gender in person. My guess this is due to running reports more than once, with no way to delete the old items from the tables. Or something not having a delete permission.

**Comment by anthonysena** [comment]
I'm unable to reproduce this in our environment. I'm in agreement with your assessment that it is likely a problem with the WebAPI account not having the proper permissions to remove entries from the tables: HERACLES_results and HERACLES_results_dist in the results schema. 

I'm going to close this since it is an old issue and note that it should be clear in the WebAPI documentation #147 that this account requires the proper permissions to delete from these tables.
