### ISSUE TITLE
Heracles "Tornado" report is messed up

### ISSUE THREAD

**Issue by pavgra** [OHDSI/Atlas#1260]
![image](https://user-images.githubusercontent.com/10010071/51647565-59233a80-1f4b-11e9-8d13-7d7b1f988448.png)

**Comment by anthonysena** [comment]
@pavgra - I think part of this issue is addressed here: https://github.com/OHDSI/WebAPI/pull/786/commits/3f1df98f73d58b57dcf4f1be7a20ca133f134ba0 since the example you provided appears to be running on BigQuery. Since #1310 is still active, I'll leave this open until that works is completed. Thanks!

**Comment by pavgra** [comment]
Right, @anthonysena , this was fixed by fixing Heracles for BQ
