### ISSUE TITLE
Extra comment line in Characterizations Strata

### ISSUE THREAD

**Issue by jswerdel** [OHDSI/Atlas#1291]
The first comment line under Strata may not be necessary and may cause users to not name the actual strata which causes a save error:
![image](https://user-images.githubusercontent.com/19151846/52129736-4d4c0e00-2606-11e9-82df-60424fd496aa.png)

**Comment by anthonysena** [comment]
Adding on to Joel's issue description here:

![image](https://user-images.githubusercontent.com/12902366/52595394-c7a53b00-2e1b-11e9-90c8-ec2d5bb02983.png)

When adding a "New Strata", the "Strata Name" field is not initialized with a default name. Furthermore, it is a bit confusing that the "Stratified By" box appears above the "Strata Name" since its not clear which is required and which is optional.

The bug here is that the "Strata Name" cannot be null in the WebAPI database so if you attempt to save a characterization with a stratum with no name, the call fails. I'd suggest we follow the same UX pattern that exists for the cohort definition inclusion rule:

![image](https://user-images.githubusercontent.com/12902366/52595621-47cba080-2e1c-11e9-9ae0-45f682f69702.png)

We will likely want to provide some default name for the stratum and then do a final check to ensure all stratum have a name before sending the payload to the server.
