### ISSUE TITLE
From cohort definition / Concept Sets, 'Copy To Concept Set Repository' allows multiple copies to be made with same name

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Atlas#1425]
### Expected behavior

From cohort definition / concept set, if I select a concept set and click 'Copy To Concept Set Repository', then a new conceptset with a unique conceptset name would be produced.  If an existing conceptset has the same name, then an error would be produced, like is done when creating a 'new concept set':
![image](https://user-images.githubusercontent.com/731930/53908065-8ec44480-401c-11e9-9901-a625495c520a.png)

### Actual behavior

A user can click 'copy conceptset to repository' multiple times and it will create multiple copies of conceptsets with the same name.

### Steps to reproduce behavior

Click 'copy conceptset to repository' multiple times, look in concept sets to see multiple instances.

**Comment by anthonysena** [comment]
Adding a little additional debugging information here: the modal concept set save dialog (`js/components/conceptsetmodal/conceptSetSaveModal`) contains logic to check if a concept set with the same name exists. In this scenario, here is where this is failing:

- Open the modal and save the concept set - it works as it should since a concept set does not yet exist with the same name.
- Perform the same operation - since the modal was instantiated already, it does not fire the code to check if the concept set exists.
