### ISSUE TITLE
[ATLAS 2.7 TEST] Record Counts

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Atlas#1534]
This might be user error or our local DB taking a nap.

### Expected behavior
Records Counts produce something other than "loading"

### Actual behavior
I haven't been successful of getting something to appear on the "record Counts" page.

![image](https://user-images.githubusercontent.com/6305439/54461093-fd528200-4741-11e9-8c91-d2b51a29a36c.png)

### Steps to reproduce behavior

1. Import 1551099
2. Click on the Concept Name to view the concept
3. Go to the Record Counts tab

**Comment by vlbe** [comment]
I also reproduced this bug

![500_concept](https://user-images.githubusercontent.com/47257857/54464802-33672480-4789-11e9-98fe-7d4db4b56eb4.PNG)

See js\pages\concept-sets\concept-manager.js 
Line 366.

**Comment by anthonysena** [comment]
@ericaVoss - I'm unable to reproduce this in our environment. It may have been environmental when you attempted this. Also, we've modified which sources cache the record counts so this may take a bit longer to return as a result.

@vlbe - I'm going to leave this issue open so that you can investigate why your record count call failed. My guess: the source does not have the ACHILLES_* tables in the results schema which hold the RC/DRC counts for that data source.

**Comment by anthonysena** [comment]
I'm going to close this out due to inactivity. @vlbe please re-open if you find that this is something other than a lack-of-data issue.
