### ISSUE TITLE
Indexing of Concept Set from 0

### ISSUE THREAD

**Issue by anemniugin** [OHDSI/Atlas#1561]
### Expected behavior
I expect to see Index of id 1 for first concept

### Actual behavior
Index of id = 0 

### Steps to reproduce behavior
Create new Cohort Definition
Add Initial Event
Import (any) Concept Set for condition era
Go to tab Concept Sets

**Comment by chrisknoll** [comment]
This is the logic:
`
				var cohortConceptSets = this.model.currentCohortDefinition().expression().ConceptSets;
				newConceptSet.id = cohortConceptSets().length > 0 ? Math.max(...cohortConceptSets().map(c => c.id)) + 1 : 0;
`
So when there are no conceptSets in the list, it defaults to 0.  We could have defaulted to 1, but 0 is a valid ID of a concept set ID.  Do you notice an error as a result of a concept_set_id = 0 in the code, or is it something that you just would like to see from an ascetic  perspective?

There might be some concern with using 0 in the ID field because sometimes we make checks like `if (id) {}` which would return false if the id has the 0 value.  But otherwise, I don't see a bug in the code.

**Comment by chrisknoll** [comment]
I'm going to close this since we have another case where we zero-base index (inclusion rules in the cohort definition), and in the case of inclusion rule index, the 0-based numbering _is_ important and necessary for the proper function. So, instead of having some things zero-based and others one-based, let's leave it both zero-based, unless there is some critical reason that concept sets should be one-based indexed.

Closing now, but please feel free to discuss.
