### ISSUE TITLE
Remove component-specific stuff from Model.js

### ISSUE THREAD

**Issue by pavgra** [OHDSI/Atlas#1565]
### Expected behavior
There shouldn't be `Model.js`. Application state required for several modules (folders under "pages") should be kept in `atlas-state.js` and all business logic should be in `services`.

### Actual behavior
Today there is a `Model.js` which appears to be a big spaghetti piece and complicates development a lot.

**Comment by chrisknoll** [comment]
Agree fully. Note, tho, that 'Model.js' actually would ahve been better nameed 'Application.js' or 'AtlasApp.js' since it is the 'root' view model of the entire atlas application. But, every little state should be in there since state/behaviors should be offloaded to sub-services or individual components.  

So, in short: still need a 'root' object class to be the top of the single-page-app, but it shouldn't have component specific behavior coded into it.

**Comment by pavgra** [comment]
There is an `Application.js` today already. That's why it even more confusing to have the `Model.js`

**Comment by chrisknoll** [comment]
Ah, that is strange.  Yes, Model.js should die.
