### ISSUE TITLE
Atlas allows to save, download and run package without NC specified which leads to error

### ISSUE THREAD

**Issue by pavgra** [OHDSI/Atlas#1644]
NCs are required for the PLE package, therefore, Atlas shouldn't allow saving the study w/o NCs + the field should be marked appropriately

**Comment by anthonysena** [comment]
To add on to @pavgra's note: negative control outcome cohorts are always constructed as part of the estimation designer in ATLAS since using negative controls is an OHDSI best practice. ATLAS should prevent users from downloading and running an estimation when a comparison does not define a list of negative control outcomes.
