### ISSUE TITLE
Add UI for asset permission editing / sharing

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Atlas#1664]
To support the UI proposed in this WebAPI issue.

https://github.com/OHDSI/WebAPI/issues/639

**Comment by pbr6cornell** [comment]
As discussed yesterday, for ATLAS 2.8 we need more complete understanding (and associated documentation) of how security functions work in ATLAS, and may require issues like this to be addressed to enable workflows that involve collaboration between individuals within a given institution,   @pavgra, what would be the best way for me to learn what current security features exist so that I can help work with you to define the additional requirements for ATLAS 2.8?

**Comment by pavgra** [comment]
Closed by https://github.com/OHDSI/Atlas/pull/1995
