### ISSUE TITLE
Characterization covariate summary table revision

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#1757]
‘Explore’ hyperlinks need to be fixed, the UI experience makes table unreadable.  Also, can’t search for words in cohort titles, since all have ‘explore’ label.

![image](https://user-images.githubusercontent.com/12902366/58133185-4830c000-7bf1-11e9-80d5-5c9064ada921.png)

**Comment by AntonStepanof** [comment]
@anthonysena Do you propose to update this table to something similar with another characterization tables(only Explore title will be link and it will below main title):
![table](https://user-images.githubusercontent.com/48437569/58269524-6da80000-7d90-11e9-816e-1ff3acdf165d.png)

**Comment by chrisknoll** [comment]
I was told that the reason for having individual links per cohort was due to that the explore popup has to have a specific target cohort to show (ie, the popup does not support showing all selected chorts side-by-side in the popup).

The idea @anthonysena  and I were thinking through was:  we can put the explore action in a separate column (non sortable, non searchable column) and this 'explore action' function would take the form of a drop-down button...clicking explore will reveal the drop-down of 'selected cohorts', and choosing one of the cohorts will reveal the explore popup.

We can reuse the component we have in cohort builder:
![ActionButton](https://user-images.githubusercontent.com/6818777/58281739-d7fd7800-7d71-11e9-85f3-85337afed45b.gif)

The list would be populated with the selected cohorts.

**Comment by pbr6cornell** [comment]
I suspect ultimately we have to do a substantial UX redesign on how to interact the characterization summary tables, to allow greater user flexibility in defining the order and selection of statistics of interest, though that may be a 3.0 goal.  But my main goal that I'd like to achieve for 2.7.2 release is that all characterization results tables are adequately formatted so that each row is readable and searchable, without the 'explore links' interfering with the experience.

In the interest of having a functional release that maintains an appropriate level of usability, a couple options to consider:

1) have one 'explore' link/button, that filters the results table to the records of interest, rather than having the modal.  There'd need to be some additional button to 'remove filter' when 'explore' is applied.  (@anthonysena , im thinking about what you had previously implemented in ActiveSurveillance)
2) have one 'explore' link/button, and have the modal show the full tabular results
3) have one'explore' link/button, and have the modal default to show the % only from the first cohort listed.

**Comment by pavgra** [comment]
@pbr6cornell , I do believe that option suggested by @chrisknoll should both provide `appropriate level of usability` and be not complicated to implement. So, if there are no concerns, we'll go for the option:

1. Separate non-sortable, non-searchable column with compact Explore button (reduced paddings to decrease height)
2. On button click:
  - If we are in single cohort mode: open Explore popup
  - If we are in comparison mode: open dropdown when a user selects a cohort of interest. Then, open Explore popup

**Comment by pbr6cornell** [comment]
I'm open to that option if we think it's easy to implement.  I want to test it as part of RC2, both for functionality and to ensure the user experience is supported.

**Comment by pavgra** [comment]
@pbr6cornell , will such approach work for you?

Single cohort mode:
![image](https://user-images.githubusercontent.com/10010071/58350785-e52f6b00-7e34-11e9-9d83-038ce5f540a5.png)

Comparison mode:
![image](https://user-images.githubusercontent.com/10010071/58350731-c29d5200-7e34-11e9-8f02-d7b7148bc96a.png)
![image](https://user-images.githubusercontent.com/10010071/58350756-d052d780-7e34-11e9-8a87-40ad704d8cbd.png)

**Comment by pbr6cornell** [comment]
I'm happy to try and test it out for the 2.7.2 approach.  Note, in that dropdown that lists the cohort name:   many cohort names will be pretty long, so we want to make sure that can handle this.

**Comment by pavgra** [comment]
I've added the following handling:
![image](https://user-images.githubusercontent.com/10010071/58488344-2ececd00-8137-11e9-8fac-0341679230b1.png)
