### ISSUE TITLE
Establish Rules around cleaning up branches after PR merge

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/Atlas#1763]
### Expected behavior
Branches should be cleaned up after PR merge is complete.

### Actual behavior
Branches are left around like litter.

### Steps to reproduce behavior
Go to the branches view in github, and observe how many branches are marked as merged, but not deleted: https://github.com/OHDSI/Atlas/branches/active.

We need to establish rules around what happens to branches after they are merged.  Who is responsible for cleaning it up?  The PR author? The PR Merger?   Someone needs to take accountability for cleaning up after the merge is complete, otherwise we'll have hundreds of branches strewn around the repository.

At the conclusion of this Issue, we will have clear rules around how branches are cleaned up, and then we will open issues to remove those branches.

**Comment by anthonysena** [comment]
I'd propose if you merge the PR into the target branch, you are responsible for deleting the feature branch. For reference, a branch can be restored via GitHub if the need arises: https://help.github.com/en/articles/deleting-and-restoring-branches-in-a-pull-request. So, in the off-chance that we need to revisit a branch before it was merged, we can always restore and review that way .

**Comment by pbr6cornell** [comment]
I agree we need to tidy up our codebase.   Since we've got a lot of dangling branches, can we please all agree to do this as part of preparation for the 2.7.2 release?   It'd be very nice to demonstrate our commitment to better development practices by having the 2.7.2 release to come from a clean repo, with clear documentation and testing.   @pavgra @chrisknoll @anthonysena @gklebanov

**Comment by pbr6cornell** [comment]
It looks like a few of the deadend branches were cleaned up, but we still have >100 branches off master right now, so that tells me we still have more spring cleaning to go.

@pavgra , can you please coordinate on the Odysseus side to clear out the backlog of your teams branches that we no longer need.

@chrisknoll - can you please do the same with the Janssen branches that are past their usefulness.

@anthonysena  - could you please look at 'likely dead' branches from others in the community and ping them to confirm they can be closed?

**Comment by anthonysena** [comment]
@chrisknoll - did a quick search and found this GitHub app that would seem to fit the bill here:

https://github.com/apps/delete-merged-branch

I did a quick test on a local repo and you can see that the "delete-merge-branch" bot automatically deleted the branch after the PR was merged:

https://github.com/anthonysena/cmtest/pull/10

The install process was easy - we'd add this app to the OHDSI organization and then activate it for the repos that want to use it (Atlas/WebAPI to start). Let me know what you think and we can get it installed and in use.

**Comment by chrisknoll** [comment]
Sounds good.

**Comment by anthonysena** [comment]
OK - installed the delete-merged-branch app so we should be set. Thanks!
