### ISSUE TITLE
Bug in instantiating treemap on ACHILLES reports in ATLAS

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Atlas#179]
When I go to 'data sources' tab in ATLAS and go to any of the drug/condition/measurement reports, the treemap does not appear. Example here: http://www.ohdsi.org/web/atlas/#/datasources/OHDSI_Sample_Database/conditions

It worked previously in ACHILLES:   http://www.ohdsi.org/web/achilles/#/OHDSI_Sample_Database/conditions

**Comment by chrisknoll** [comment]
This template load is returning a 404:
http://www.ohdsi.org/Atlas/js/components/datasources/templates/attributeValueTable.tmpl.html

As you can see here, it's trying to load a template from /atlas/js/components/datasources... but on ohdsi.org site, atlas is under /web/atlas.  We should be able to load the template using a relative path instead of an absolute path.

**Comment by chrisknoll** [comment]
The issue is in this line:

**Comment by mark-velez** [comment]
This appears to be a regression bug. Commit [Merge branch 'profile'](https://github.com/OHDSI/Atlas/commit/b2bf5313a4cf53cde806b95e8d159f49868ee68f#diff-087afee98ec1462d08910a6e70fa4406) reverts [several commits](https://github.com/OHDSI/Atlas/commits/master/js/components/data-sources.html) made by me and @juh7007 since early March.
