### ISSUE TITLE
Entity list sorting fix

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#1796]
Related to #1571 and #1795, let's apply the approach used for the cohort definition list to the other areas of the application that list entities.

**Comment by chrisknoll** [comment]
I don't think this will be necessary.  The other places in the application uses an integer-based serialized form for dates while cohort definition service is returning a formatted date string as the date.

The source of the issue was this conversion between a date-string to a comparable date value, which doesn't happen when the source format of the date/time is an int.

Long term solution would probably be to update the cohort definition service to return the same datetime format that the other services (which were developed after cohort definition service).

**Comment by chrisknoll** [comment]
Actually, I should slightly reverse myself:  part of the changes was realted to fixed-width columns, so I can apply those styles to the columns. I'll reopen and do that under this issue.

**Comment by chrisknoll** [comment]
Closing this, I checked master, and all the entity tables have fixed width columns for the dates, so I think everything covered in this issue is resolved.
