### ISSUE TITLE
Atlas shouldn't allow special characters in input fields

### ISSUE THREAD

**Issue by ambuj369** [OHDSI/Atlas#1922]
Expected behavior: Should run without any failure or delay.

Actual behavior: Application gets hanged or some features don't work as expected

Steps to reproduce behavior:
1. Cohort > New Cohort
2. Enter the HTML text in cohort name
3. Save
4. Come back to cohort list and a button will be there to click.

I am reporting this because I have found this scenario which may cause issues with Atlas workflow and other multiple issues in WebAPI schema, to fix it, one has to delete the entries in DB.
Attached screenshot

-Ambuj
![C1](https://user-images.githubusercontent.com/47858365/59673488-0ccce580-91df-11e9-874d-1571169aba37.jpg)

![C2](https://user-images.githubusercontent.com/47858365/59673505-13f3f380-91df-11e9-8a3f-5592aabf04ad.jpg)

**Comment by pavgra** [comment]
@chrisknoll , I believe, we discussed this once: might be reasonable to re-iterate?

**Comment by chrisknoll** [comment]
Sure thing, I thought this was all handled via the XSS filtering on datatables.  Is it not working?

**Comment by vlbe** [comment]
@pavgra @chrisknoll 
Yes, we have xss filtering on datatables. The problem is that we have whitelist of tags in xssConfig, because we use a/button/span etc tags in table cells. So we have two options:
1) Add custom xss options to every column with whiteList of tags which are used in custom render of this column
2) Replace default textInput binding with custom binding which will sanitize html in input fields

**Comment by pavgra** [comment]
I propose to escape content which is passed into the function which renders the link

**Comment by chrisknoll** [comment]
I've added an 'xssSafe' option to the datatable binding which allows certain columsn to not apply the XSS filtering to it (in such cases such as columns where we output buttons).  We can tighten up the XSS filters on user-input columns to be more strict, and mark those other columns where we do allow buttons/links/etc to be 'xssSafe' and those columns will be left as-is.

I think we should leverage the XSS function of the binding to guard against these XSS issues.   I think it can be used to ignore elements like buttons so that if someone puts a button in their text, it won't render.
