### ISSUE TITLE
Active Directory groups mapping issue

### ISSUE THREAD

**Issue by olga-ganina** [OHDSI/Atlas#1952]
Table is not updated when adding group to the role .

**Comment by vlbe** [comment]
### Expected behavior
Added group is shown in table

### Actual behavior
Added group is not shown in table

### Steps to reproduce behavior
1) Go to Configuration
2) Click "Import users from LDAP/AD" button
3) Click "Import Now" button
4) Click on some row in table
5) Search for group, select some and click "Set" button
6) Selected group is not shown in "Group Name" column.
