### ISSUE TITLE
Cohort Definition - Condition Type Filter

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#196]
The condition type filter does not present any options when attempting to use it from within a cohort definition.

**Comment by anthonysena** [comment]
This is not a bug - it is just entirely obvious how to do this. Here are the steps to reproduce the problem and the "work-around":

- Create a new cohort definition. Within it, add a condition occurrence event. Then add a criteria attribute of "Condition Type". 
- Click the "Add" button after "Condition Type is:" which will display a modal window with options.
- The window will not show any options:

![image](https://cloud.githubusercontent.com/assets/12902366/22566073/92d02e26-e958-11e6-9a26-2053c814742c.png)

Here are the additional steps required:

- In the drop down, select "Type Concept". 
- Put the cursor in the "Search..." box and hit enter which will retrieve all type concepts
- Once the results return, use the "Filter records:" to find the "condition type" concepts as shown:

![image](https://cloud.githubusercontent.com/assets/12902366/22566059/828dd388-e958-11e6-9948-43819f8bb9f5.png)

I'm going to close this and open a new enhancement so we can think about making this experience closer to doing a regular vocabulary search.

**Comment by chrisknoll** [comment]
Hey @anthonysena , the issue is they changed the domain type of concept types to be 'Type' or 'Concept Type' (I need to look it up) but the UI is defaulting to 'condition concept type'.  The easy fix is to just set the correct default.

As far as making it work like other vocabulary searches: the regular vocabulary search is tightly coupled to a concept set expression (which this isn't).  The mode in question is optimized to look for concepts of a type that is very short (such as genders, or condition concept types). these types of concepts are not the types that would exist in the concept_ancestor table.  So, i'd stick with this user experience for selecting concepts and just fix this issue by setting the correct domain.

**Comment by anthonysena** [comment]
Got it - thanks for the explanation. I took your advice and updated the domain to be "Type Concept" which does the trick and at least provides some defaults in this scenario. We can further discuss the other approach in the other issue #327.
