### ISSUE TITLE
Cohort definition Ux comment, red x for removing attributes confusing to a user

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Atlas#1999]
### Expected behavior

Kristin Kostka doesnt complain about atlas iu during live demo in tutorial

### Actual behavior

Kristin said she is confused why theres a red x next to attributes, because it suggests the attribute doesnt belong or is stopped.

I havent been confused by this myself but its probably worth considering if alternative ui designs may be less confusing.

### Steps to reproduce behavior

Red x appears next to all optional attributes

**Comment by kmkostka** [comment]
Worth noting this is actually feedback from the Building cohorts session at the OHDSI Face-to-Face in Cleveland. I'm just a messenger! ;)

**Comment by chrisknoll** [comment]
The intent of the 'x' is to follow other UI patterns for 'removing element from UI'.  For example: you want to remove an open window from your desktop, you have an 'x' in the top right.  If you want to close the current tab in your browser, there's an 'x' to remove the tab.  If you want to remove a label from this git issue, there's an 'x' to remove it.  

We also use the 'x' symbol in other elements of the UI to indicate that the element should be removed.  If we're thinking about making this one change, we will need to ensure that it is consistent across all elements.

Other symbols that have been suggested in he past have been the 'do not enter' symbol (ie: red circle with a slash across it), but this was deemed not appropriate since that symbol represents something being 'forbidden' and not indicative of 'removing from selection'.  So, the 'x' was the most consistently used/understood symbol.

So, if we want to change the 'x' = remove behavior of the UI, I'd want to see other examples of any suggested alternative in actual practice.  I'm very firm against putting  words like 'remove' in place of the symbol: the symbol is supposed to represent an action.

One possibility: a 'minus' sign next to each atribute (maybe a circle around a minus to make it more visible', since next to 'add' we have a '+', would it make sense to have the inverse be '-'?

**Comment by fdefalco** [comment]
Here is what fontawesome (the current source of our icons) suggests for "remove".

https://fontawesome.com/icons?d=gallery&q=remove&m=free

or delete

https://fontawesome.com/icons?d=gallery&q=delete&m=free

**Comment by chrisknoll** [comment]
Thank you, those 2 examples prove my point (but probably not the way you expect):

If you will notice what symbol is applied to the selected filters:
![image](https://user-images.githubusercontent.com/6818777/62480832-dd6a3c00-b77e-11e9-92a0-0bb693ef3828.png)

So,another good example where 'x' indicates 'to remove'.  Thanks!

**Comment by chrisknoll** [comment]
Here is another one, straight out of Wrike:
![xToRemove](https://user-images.githubusercontent.com/6818777/62482891-6a63c400-b784-11e9-9207-bd92ef910581.gif)

Another example of 'x' to remove, but with the addition that the remove element is only visible when hover over.  I don't really like this approach: when I first looked at the UI trying to remove assigments, I coudln't find  where I needed to go to remove the assigment.  Only with some hunt-and-click (or hunt and hover) was I able to reveal where the function was.  So, I don't like the 'hidden' nature of the remove function, but I do agree with the choice of the 'x'.

**Comment by kmkostka** [comment]
In these examples, the ‘X’ is at the end of the selection not the beginning.

The discussion at the OHDSI F2F was that an ‘X’ at the beginning of the selection reads, to some users, as “NOT [selection]”. In this case, it’s not the X itself but the position of that causes confusion.

**Comment by chrisknoll** [comment]
Right, good point, and that gives a bit more clarity about the issue: it's not the 'x' itself is confusing, it's the position.

The purpose of the position is that the criteria length can vary in width (and across lines) so the idea of putting the 'x' on the left was to have nicer arrangement on where to find the 'remove' icons instead of having to scan across the width of the UI to find it.

This is what we have:
![DefaultPlacement](https://user-images.githubusercontent.com/6818777/62486146-75225700-b78c-11e9-95fd-66b38f4b6fc7.png)

And this is photoshopped to appear with right-side deletes:
![RightPlacement](https://user-images.githubusercontent.com/6818777/62486175-866b6380-b78c-11e9-8168-bfcf5d926b71.png)

Or if we aligned the X's on the right side (effectively moving the column from left-colum to right-column for the remove indicators):
![Right-AlignedPlacement](https://user-images.githubusercontent.com/6818777/62486295-e235ec80-b78c-11e9-8660-a7cf3bad65b1.png)

Right-alingment, while easier to find, really separates the 'x' from the element it's removing, so I don't recommend that.  And just tagging it to the right side-end of the criteria means you have to do a little more mouse movement to get to the location of the element you want to remove.

This is why we settled on the arrangement.  I am thinking that the change of the symbol to '-' won't solve the issue either, since we're concerned with left-side alignment such that the users would read the 'x' as part of the criteria as 'not', but all I can say on this point is that everything else in the cohort expression is spelled out (we say 'greater than' and not '>='.  We say 'not' and not 'x'.  But if anyone has an idea about positioning of the 'x' elements, please mock up a drawing and post it here so we can evaluate it.

**Comment by chrisknoll** [comment]
I'm going to add tool-tips to the remove icons so that it's clear what it does.
