### ISSUE TITLE
[Bug] Estimation module - Outcome model settings

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Atlas#2010]
### Expected behavior
- Changing Yes to No, should allowing saving specifications
![image](https://user-images.githubusercontent.com/13936600/62790363-f7669000-ba98-11e9-91cd-25ed4157575d.png)

- save button should turn green
![image](https://user-images.githubusercontent.com/13936600/62790433-211fb700-ba99-11e9-89c8-b1c1ae8aa223.png)

- after saving, specification should stay as specified - i.e. No

### Actual behavior
When specification changed, save button does not turn green
![image](https://user-images.githubusercontent.com/13936600/62790491-414f7600-ba99-11e9-9c93-a1c912721ecf.png)

- only way to get save button to turn green is change one of the labels

- even after saving, specification reverts back to YES.

### Steps to reproduce behavior
- follow the steps above in 
ATLAS Version 2.7.2 Release Notes 
WebAPI Version 2.7.2 Release Notes

@anthonysena @schuemie

**Comment by anthonysena** [comment]
@gowthamrao - so I've found the issue here which is both a bug and a likely UX improvement.

The setting in the outcome model: _Should the regression be conditioned on the strata defined in the population object (e.g. by matching or stratifying on propensity scores)?_ is based on a choice made in the Propensity Score Adjustment section. If you choose "None" for _Do you want to perform matching or stratification?_ then the setting for conditioning does not apply. In the case when we opt to use Stratification for the PS adjustment, then the regression is always conditioned on the strata. When we choose matching for the PS adjustment, then we can decide to condition the regression. 

In the case we discussed internally, your analysis is using stratification for the PS adjustment. So, the UI is overriding your choice for the outcome model arguments which is a both a bug and a misleading user experience. Just noting it here since we made some adjustments to the estimation for per #1659 and I'd like to make sure that we correct this behavior in a subsequent update.

**Comment by jamieweaver** [comment]
Conditional outcome model is required when using PS stratification or 1:n variable ratio PS matching, but it can be appropriate to set unconditional outcome model when using 1:1 PS matching. Is the UI overriding user input and setting conditional outcome model = YES for any PS matching approach?

**Comment by ssuvorov-fls** [comment]
@anthonysena 
Could you explain what should be done?

**Comment by anthonysena** [comment]
@ssuvorov-fls - in the Estimation -> Analysis Settings -> Propensity Score Adjustment section:

If a user chooses either "matching" or "stratification", then in the "Outcome Model Settings" section, the option that says

"Should the regression be conditioned on the strata defined in the population object (e.g. by matching or stratifying on propensity scores)?"

This yes/no drop down should be available to the user to select. I believe this option is being overridden by some defaults so best to take a look and see how that is working to start and I can answer questions around the behavior here. Thanks!

**Comment by ssuvorov-fls** [comment]
@AnthonyMolinaro 
It seems to be a bug. When user chooses "matching" or "stratification" then the dropdown "Should the regression be conditioned on the strata defined in the population object (e.g. by matching or stratifying on propensity scores)?" is automatically set to true. If the user set it to false, it will be saved correctly in the database. But when user will load it later it will be again set to true only on ui.
I can remove automatic setting at all or when the user loads estimation

**Comment by AnthonyMolinaro** [comment]
@anthonysena  I think the last message was for you.  : )

**Comment by ssuvorov-fls** [comment]
@AnthonyMolinaro Sorry ) Yes, it's for @anthonysena

**Comment by anthonysena** [comment]
> I can remove automatic setting at all or when the user loads estimation

@ssuvorov-fls - yes, please remove that automatic setting. Thanks!
