### ISSUE TITLE
Cancel cohort characterization jobs - before job has started

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Atlas#2021]
### Expected behavior
able to cancel cohort characterization job at anytime

### Actual behavior
can cancel cc job after 'started'
cannot cancel cc job before 'started' i.e. in starting/que

### Steps to reproduce behavior
run jobs and check the UI for jobs that have not started but are in que.

**Comment by anthonysena** [comment]
@gowthamrao - just want to clarify since I think this scenario only happens when you have hit the maximum number of jobs in the queue? For example, there are 10 active jobs running and the maximum # of jobs allowed is 10. When you start the 11th job (i.e. a characterization), instead of the "generate" button turning to "running" it may not change state to the fact that the job is queued. Do I have this right?

**Comment by gowthamrao** [comment]
Yes @anthonysena  you have captured the issue more accurately.
