### ISSUE TITLE
ATLAS designs / analyses must highlight required parameters before allowing users clicking generate / execute buttons

### ISSUE THREAD

**Issue by gklebanov** [OHDSI/Atlas#2044]
### Expected behavior
All ATLAS analyses (cohorts, characterization, IR, PLE, PLP, TxPathways) should highlight required parameters before allowing users clicking generate buttons. If user has not entered everything, he should be guided to complete design

I would propose to have a flag, or check that would allow to return analysis status as "valid/invalid" as well - to be by execution automation

### Actual behavior
In many cases, the analyses allow users to click generate button even if required parameters have not been completed. The execution says "completed"  but it actually fails - not obvious and the only way to see it is to decipher logs. So, exception handling should be documented and consistent across ATLAS as well (will create another GitHub issue)

![image](https://user-images.githubusercontent.com/26966141/65509160-d2d74380-de9f-11e9-8137-40109cebc82f.png)

![image](https://user-images.githubusercontent.com/26966141/65509286-1e89ed00-dea0-11e9-9cd7-97686f83d1d2.png)

![image](https://user-images.githubusercontent.com/26966141/65509331-3c575200-dea0-11e9-8177-7338b4b192e0.png)

@pbr6cornell  - this is causing a lot of headaches for many people today, I propose we target it in 2.8 but will seek your confirmation since it will impact our scope

**Comment by anthonysena** [comment]
For the Estimation & Prediction modules, there is a check that is performed in the Utilities section so that you can only download the study package once you have provided the minimum required inputs. We should probably do the same check for the executions section for Estimation & Prediction.

This issue is related to #1811, #1846, and #944 for Estimation since we'd like to have a series of checks that we can use to notify users of any obvious problems.

**Comment by olga-ganina** [comment]
Looks like it is also related to #387

**Comment by anthonysena** [comment]
This issue bundles together validation for several modules in ATLAS:

1. Cohort Definitions
2. Characterizations
3. Incidence Rates
4. Pathways
5. Estimation
6. Prediction

For Estimation/Prediction, let's use #994 to track the required checks for generating/downloading the study package as this list of checks may be lengthy. For the other ones, let me take a first shot at what should be required and if easier spin off different issues to address each one:

#### Cohort Definition
- Cohort entry event: This is required but also tricky since an event may be specified but either incomplete or invalid. Tagging @chrisknoll for thoughts on how we might validate a cohort definition. I know there is an open issue for circe to document the "checks" that are performed on a cohort definition (although I'm unable to find it at the moment) so perhaps that is something we can leverage here.

#### Characterizations
- Must have >= 1 cohort definitions specified
- Must have >= 1 feature analyses specified

#### Incidence Rates
- Must have >= 1 target cohorts specified
- Must have >= 1 outcome cohorts specified
- Must have a valid time-at-risk (already addressed via #1008)  

#### Pathways
- Must have >= 1 target cohorts specified
- Must have >= 1 event cohorts specified
- Combination window must be >= 0
- Minimum cell count must be >= 0
- Maximum path length must be >= 1 and <= 10 (we should revise this to a drop down since the max supported by the back end is 10)

**Comment by ssuvorov-fls** [comment]
@gklebanov @anthonysena 
Errors are now shown in "Messages" tab (as it is done for cohort definitions)
Do you agree?
