### ISSUE TITLE
SQL Injection possible in cohort definition

### ISSUE THREAD

**Issue by eldarallakhverdiiev** [OHDSI/Atlas#2129]
When designing cohort based on Specimen/ Device Exposure, user can use  Source Id attribute
which is a place for any sql injection.

![image_2020_02_13T15_40_49_514Z](https://user-images.githubusercontent.com/25959256/74452660-5db8da80-4e4f-11ea-93fc-a2e571dc8dc1.png)

![image_2020_02_13T15_39_46_444Z](https://user-images.githubusercontent.com/25959256/74452656-5d204400-4e4f-11ea-889c-7de3bfb21411.png)

**Comment by YaroslavTir** [comment]
@chrisknoll We want to release web-api 2.7.7 with the sql injection fix, but the fix is part of the 1.9.0 version of the circe. This one is under development, and we cannot just bring the snapshot version into web-api. So my question is
When do you plan to release 1.9.0? and if it is not going to happen soon, can we introduce 1.8.4 version of circe only with this sql-injection fix?

**Comment by chrisknoll** [comment]
1.9.0 was going to come in time for the WebAPI 2.8 relase.

If you'd like, I can create a hotfix branch off of the 1.8.3 release and you can PR onto that.

Then I can release the 1.8.4 release with that hotfix.

**Comment by chrisknoll** [comment]
You can make the changes on this branch: https://github.com/OHDSI/circe-be/tree/1.8.4-hotfix

**Comment by chrisknoll** [comment]
This has been released in 1.8.4. Please let me know if you have any questions.
