### ISSUE TITLE
Occurrence end date decreases by one day after saving 

### ISSUE THREAD

**Issue by KSadomtsev** [OHDSI/Atlas#2148]
Before saving:
![image](https://user-images.githubusercontent.com/56290675/76316727-1a397b00-62ec-11ea-86b6-23e62042251f.png)
After saving:
![image](https://user-images.githubusercontent.com/56290675/76316779-2a515a80-62ec-11ea-9fa6-3bb0520c5d73.png)

wrong date in PUT request:
{CodesetId: 0, OccurrenceStartDate: {Value: "2019-12-31", Extent: "2020-03-29"

**Comment by chrisknoll** [comment]
Just some background on this: I've seen problems like this one when dealing with date-input fields where a timezone for the local client causes some conflict where it resolves into a different date after ignoring the timezone.  I've tried to address this in the past by just always looking at a the day/month/year of the field (ignoring any timezone adjustment) but this problem looks like that issue is happening again.  The root of it involves the date-picker component which we don't have direct control over how the localized timezone is returned when the user clicks on a date.  But we should be intercepting the result and re-formatting it to a simple yyyy-mm-dd format.
