### ISSUE TITLE
There is no message about generating reports

### ISSUE THREAD

**Issue by jungsungjae** [OHDSI/Atlas#219]
After click the generate button on the cohort reporting menu,
I can check out job status.
But, there is no any message meaning job has launched.
So, I feel confused if they have launched or not.
When I go back to cohort reporting menu from the other page,
there are images that represent running status.

In addition,
stop button would be helpful to suspend a running jobs.
Is there any ways to stop a running jobs now?

**Comment by t-abdul-basser** [comment]
I agree: a message would be helpful.

There is no way to stop it currently in the UI.

**Comment by anthonysena** [comment]
This issue has 2 parts: 

1. Cohort reporting should provide feedback on report generation. This has been addressed as part of this work https://github.com/OHDSI/Atlas/commit/f332e000103a625c3990dd2f7eef99a79f83d23e and will be available shortly. 
2. Provide the ability to cancel a job. I'm going to link this to another related issue: #246 

I'm going to close this since part 1 is fixed and part 2 will be tracked under #246.
