### ISSUE TITLE
Incident Rates: Remove the ability to change a design if you lack permissions

### ISSUE THREAD

**Issue by olga-ganina** [OHDSI/Atlas#2194]
Parent task #2174 

### Expected behavior
If a given entity is locked since I do not have rights, I should not be able to make changes that would require a save action.

### Actual behavior
IR: Target/Outcome cohort lists should disable the ability to remove. The Time At Risk settings should be read-only. The Add Study Window/New stratify buttons should be disabled. On the concept set tab, the buttons should be disabled. The generation tab should ensure all buttons are disabled to remove results and to re-generate.

**Comment by aklochkova** [comment]
@anthonysena in my PR I didn't disable `re-generate` and `generate` buttons but only hid a `remove` one. Users can't run a generation with a changed design before it's saved and they can't save it due to lack of permissions. So it's safe from changes.
Is it enough or should I hide generation buttons and add new permissions to WebAPI to protect it?

**Comment by aklochkova** [comment]
@anthonysena could you please review my previous comment about `generate` buttons?

**Comment by anthonysena** [comment]
Let's handle it in the review of #2220 - I suspect your approach will be fine as you described.
