### ISSUE TITLE
cannot unselect multiple concepts in bulk

### ISSUE THREAD

**Issue by liyupeng111** [OHDSI/Atlas#2229]
### Expected behavior
should be able to unselect all concepts in bulk by clicking the top 'shopping cart' button

### Actual behavior
no response after clicking the top 'shopping cart' button

**Comment by chrisknoll** [comment]
There concept set editor has been revamped, so I'm going to close this out for now. we have the ability to do bulk selection for the concept set items (for removal, excluding, descendants, etc) in this PR: #2385.  However, we won't be implementing a 'select all' on search results or in concept hierarchy views due to that we want to discourage the adding of thousands of concepts to a concept sets when each choice should be evaluated before inclusion.
