### ISSUE TITLE
Atlas localization

### ISSUE THREAD

**Issue by anton-abushkevich** [OHDSI/Atlas#2494]
## Project Overview

Implementation of the localization support: support for a local language and locale specific date/time and other common formatting. The following is to be completed:

- Extract all text and replace with placeholder labels
- Have an ability to specify the target locale (using the ISO language code), with English (US) being a default language
- Develop a mechanism to read and display text as specified in language settings
- Beside default English, add Korean, Chinese and Russian localization 
 

## Technical implementation

- Files with translations are stored at the backend
- At UI starting or if a user switches the locale the request with “lang” parameter which contains locale code is sent to the backend
- Depending on the value of the “lang” parameter backend sends the response with an object containing necessary translations
- At the frontend this object is loaded in the shared state
- All hardcoded texts are replaced with variables that recalculate after changing of the object with translations.

**Comment by chrisknoll** [comment]
Thanks for posting the overview.  We're trying to make it the normal procedure that the Issue describing the feature is posted in advance of the actual PR so that there's opportunity to discuss and comment on the functionality, but in this case I think this was being planned for a long time, and we didn't have a process for making new planned features. But, going forward, the process is Issue -> comment and review -> pr -> code review.

Thi is a great feature, it's something that will let our collaborators work in their own native language, so I very much appreciate the work on this and also the value that this feature brings.

One question about the functionality of the selected locale:

> At UI starting or if a user switches the locale the request with “lang” parameter which contains locale code is sent to the backend

My question is: does the user need to select a locale?  When I initially thought about addling localization to atlas, I was looking at the `i18n` plugin from requireJS, which uses javascript to determine the current locale of the browser, and then fetches resources based on that.  You can see the code [here](https://github.com/requirejs/i18n/blob/6ef197793a713a21f2e74f98e372c161aad3490f/i18n.js#L123), but the code looks like this:

```
 ((navigator.languages && navigator.languages[0]) ||
   navigator.language ||
   navigator.userLanguage).toLowerCase();
```

I stripped out some i18n-plugin logic, but I believe this is the basic form of detecting current locale from the browser.  Would that be more seamless to the user to just detect the locale instead of making the user choose it?

**Comment by anton-abushkevich** [comment]
@chrisknoll Thank you.

> Would that be more seamless to the user to just detect the locale instead of making the user choose it?

I agree. I added default locale detection (see js/services/I18nService.js:14).
