### ISSUE TITLE
RC and DRC in Concept sets in a cohort definition are different from that of Vocabulary search

### ISSUE THREAD

**Issue by rwpark99** [OHDSI/Atlas#254]
RC and DRC in Concept sets in a cohort definition are different from that of Vocabulary search. For example, when I open [HA1c Lab Result] concept in [eMERGE PheKB Type 2 Diabetes phenotype algorithm (Northwestern University) oldV3] cohort definition, then it show as follow in our AUSOM (Camel DB - our new DB, not opened to public yet):

Id	Code	Name	Class	RC	DRC	Domain	Vocabulary
3007263	17855-8	Hemoglobin A1c/Hemoglobin.total in Blood by calculation	Lab Test	0	0	Measurement	LOINC
3005673	17856-6	Hemoglobin A1c/Hemoglobin.total in Blood by HPLC	Lab Test	0	0	Measurement	LOINC
3004410	4548-4	Hemoglobin A1c (Glycated)	Lab Test	0	0	Measurement	LOINC
3003309	4549-2	Hemoglobin A1c/Hemoglobin.total in Blood by Electrophoresis	Lab Test	0	0	Measurement	LOINC

But, when I search [hemoglobin A1c] in Vocabulary, then it shows:
Id	Code	Name	Class	RC	DRC	Domain	Vocabulary
40789263	LP16413-4	Hemoglobin A1c	LOINC Hierarchy	0	363,624	Measurement	LOINC
3034639	41995-2	Hemoglobin A1c [Mass/volume] in Blood	Lab Test	363,624	363,624	Measurement	LOINC
40775446	LP100945-7	Hemoglobin A1c | Bld-Ser-Plas	LOINC Hierarchy	0	363,624	Measurement	LOINC

As a result, when I run the cohort, then the # of enrolled patients to the cohort is 0. I am not sure whether the 0 count originated from this mapping or search stuff or by the strict enroll criteria..

**Comment by chrisknoll** [comment]
@rwpark99 ,
  It looks like the concepts used in the concept set are not the ones you found when you did your [hemoglobin A1c].  Your search results found classes of 'Hierarchy' which isn't what the ETL should map to but rather the descendant concepts that are under the Hierarchy LOINC concept you should see mappings.  To see what those are, go back to your Vobabulary search, and when you search for [hemoglobin A1c], select the concept 40789263 LP16413-4 Hemoglobin A1c, and this will switch you to the 'concept details' view. from here you can look at the descendant concepts and understand which LOINC codes are directly mapped to, which are the ones where RC is greater than 0.

Notice that the concept that was not a Hierarchy in your search was this one:
3034639 41995-2 Hemoglobin A1c [Mass/volume] in Blood Lab Test 363,624 363,624 Measurement LOINC

But this wasn't in your cohort definition concept set for [HA1c Lab Result].  So, if you want to find that concept in your cohort definition, you need to add he concept 3034639 to the cohort definitions concept set, and you also may need to alter the cohort definition Measurement criteria to look for the correct units (whatever Mass/Volumne might be reported as).

To do a more advanced troubleshooting:  you can use the generated sql under the Export tab -> SQL tab in Atlas in the cohort definition.  It gives you the database-specific query (either MSSQL, ORACLE, PostgreSQL or Reshift) that you can alter to do the query directly on your data, and run it one part at a time to see which step in the query returns 0 rows.  That will clue you in as to is it a voabulary problem, or a problem with the data that was ETLed into your CAMEL DB.

**Comment by rwpark99** [comment]
Thank you for your information.
Then, does it means that the records only in DRC but not in RC are not included in the cohort definition?
So I need to modify the concepts definitions in the cohort to included the records only in DRC?

**Comment by chrisknoll** [comment]
Any if a concept has a DRC, then if you use that concept's descendants in the concept set expression, then you will get all the rows that the DRC counts.   If you only select the concept (without descendants) then only the rows that were counted in the RC count will be included.

The reason why I would not use a concept that has a DRC > 0 but a RC = 0 (example: the LOINC hierarchy concept which is a hierarchy for Hemoglobin tests) is that in this case:
Id Code Name Class RC DRC Domain Vocabulary
40789263 LP16413-4 Hemoglobin A1c LOINC Hierarchy 0 363,624 Measurement LOINC

You'll find 363,624 rows of descendant concepts of this LOINC concept, but because RC is 0, nothing maps directly to that concept.

The reason why you want only those with RC > 0 is that you will probably need to look for specific measurement values of the blood tests. I pulled up the descendants of the 40489263 LOINC hierarchy concept here:
http://www.ohdsi.org/web/atlas/#/concept/40789263

This is the descendants:
```
3003309	4549-2	Hemoglobin A1c/Hemoglobin.total in Blood by Electrophoresis	Lab Test	0	0	Measurement	LOINC
3034639	41995-2	Hemoglobin A1c [Mass/volume] in Blood	Lab Test	0	0	Measurement	LOINC
3005673	17856-6	Hemoglobin A1c/Hemoglobin.total in Blood by HPLC	Lab Test	0	0	Measurement	LOINC
40765129	62388-4	Hemoglobin A1c/Hemoglobin.total in Blood by JDS/JSCC protocol	Lab Test	0	0	Measurement	LOINC
42869630	71875-9	Hemoglobin A1c/Hemoglobin.total [Pure mass fraction] in Blood	Lab Test	0	0	Measurement	LOINC
3007263	17855-8	Hemoglobin A1c/Hemoglobin.total in Blood by calculation	Lab Test	0	0	Measurement	LOINC
3004410	4548-4	Hemoglobin A1c (Glycated)	Lab Test	0	0	Measurement	LOINC
40775446	LP100945-7	Hemoglobin A1c | Bld-Ser-Plas	LOINC Hierarchy	0	0	Measurement	LOINC
40762352	59261-8	Hemoglobin A1c/Hemoglobin.total in Blood by IFCC protocol	Lab Test	0	0	Measurement	LOINC
```

Are all these concepts mesuring the same thing with the same units?  If not, then you'll have to look for each of them individually looking for the specific measurement values for your definition.

However, if you are just trying to find people who had one of these tests, then you can just put the single LOINC hierarchy in a concept set, select the descendants, and any Measurement under that concept will be found.  I've created such a concept set on ohdsi.org for you to see:
http://www.ohdsi.org/web/atlas/#/conceptset/8282/included

-Chris

**Comment by rwpark99** [comment]
I didn't understand how the Concept sets works. Now it's more clear to me. Thank you very much.
