### ISSUE TITLE
remove repository selectors from concept set and cohort definition browsers

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Atlas#260]
The original intent of the repository selectors was to allow an installation of ATLAS to be configured with multiple WebAPI services available to interact with and so they appear on the browser pages (the views you arrive at by clicking on the left menu items).  Today the feature set is incomplete and so switching between repositories is not possible and yet this component remains on the pages and only creates confusion.

The one place where a selector is still required is in the concept set selector presented inside a cohort definition.  In this case the user can select a concept set that is defined in the cohort definition or from the repository.  I believe this is the only case where this part of the interface should remain available.

**Comment by chrisknoll** [comment]
Actually they can remove that selector from the cohort definition because you can get to the 'inner' concept sets of the cohort via the dropdowns in the criteria.  Removing this 'repo or cohort' selector from the component would clean it up immensely and remove some of the confusion that comes up when people first load from a repo and then have to go back to the same dialog to flip it over to the cohort to chose the previously imported concept set.

**Comment by anthonysena** [comment]
Fixed in https://github.com/OHDSI/Atlas/commit/c37de81cd1d06cdf61fea9693ae3b4b2d67cf29f
