### ISSUE TITLE
SqlRender Developer missing create table 

### ISSUE THREAD

**Issue by altosaar** [OHDSI/Atlas#2649]
### Expected behavior
Being able to copy target translation to clipboard in https://data.ohdsi.org/SqlDeveloper/ without manually adding the additional lines to create the table.

### Actual behavior
Needing to add the additional lines to create the table.

### Steps to reproduce behavior
1. Export the OHDSI SQL from a cohort definition:
![image](https://user-images.githubusercontent.com/5317244/146553804-b0632d5d-99de-4e3a-90c6-d677d32f4509.png)
2. Paste it into https://data.ohdsi.org/SqlDeveloper/
3. Copy the target to clipboard
4. Paste into Microsoft SQL server management studio or another IDE
5. Add the following lines so the SQL query can actually run:
```
CREATE TABLE target_database_schema.target_cohort_table (
	cohort_definition_id INT,
	cohort_start_date DATE,
	cohort_end_date DATE,
	subject_id BIGINT
);
```

This should be a quick fix of just adding the above lines to Atlas in the export -> OHDSI SQL tab.

**Comment by anthonysena** [comment]
Hi @altosaar - thanks for posting this issue. The reason why the `cohort_table` is not explicitly in the SQL is due to the fact that WebAPI requires that the `cohort_table` is created in the results schema before you can generate the cohort. So when the SQL is exported, the assumption is that someone/something has already set up the cohort table. This may be confusing but is by design.
