### ISSUE TITLE
Bug in Spark SQL generation for Incidence Rate Analysis in 2.11

### ISSUE THREAD

**Issue by TomWhite-MedStar** [OHDSI/Atlas#2699]
### Expected behavior
SQL generated by Incidence  Rate Analysis::Utilities::SQL::Spark should run with standard @-variable substitutions on DataBricks.

### Actual behavior
The queries fail at the sections:
` from @temp_database_schema.@cohort_table`
because this should be referencing the cohort table in the results database into which the results of the cohorts were already written.  Those should not reference the temp database.

The IR analyses run to completion correctly when those sections are replaced with this code:
`from @results_database_schema.@cohort_table`

### Steps to reproduce behavior
(1) Import attached IR JSON file
(2) Review generated SPARK SQL for the IR (see IR_2.sql.txt)
   -- Issues are on lines 33, 38, and 68
(3) Note that the cohorts themselves run fine (see cohort_17.sql.txt)
  -- Their final writing to the results cohort table happens to use this code, which is fine as-is:
      `@target_database_schema.@target_cohort_table`

[incidence rate valsartin tutorial.json.txt](https://github.com/OHDSI/Atlas/files/8613934/incidence.rate.valsartin.tutorial.json.txt)
[IR_2.sql.txt](https://github.com/OHDSI/Atlas/files/8613963/IR_2.sql.txt)
[cohort_17.sql.txt](https://github.com/OHDSI/Atlas/files/8613964/cohort_17.sql.txt)

**Comment by anthonysena** [comment]
@TomWhite-MedStar - I believe what is happening here is that on the back-end, we're copying the cohort (cohort_17 in this case) to the `@temp_database_schema` so that we can use it when running the IR analysis. Reason being: we use the `@temp_database_schema` for this operation so we don't lock the main `@results_database_schema.cohort_table`. So, I believe it is fine to substitute the `@temp_database_schema` with `@results_database_schema`. Hope this helps!
