### ISSUE TITLE
Probable mismatch between atlas ui and human readable text

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Atlas#2721]
### Expected behavior
For the UI and human readable text to match the SQL. I suspect I think it should say (based on the SQL)

```
WHERE C.OBSERVATION_PERIOD_START_DATE <= DATEFROMPARTS(2011, 12, 31) and C.OBSERVATION_PERIOD_END_DATE >= DATEFROMPARTS(2011, 12, 31)
```
Does that mean - the observation_period should overlap with 2011-12-31? i.e. Circe should say **'Restrict entry events to that are part of observation period that overlaps with December 31, 2011.'**

### Actual behavior
Circe says **'Restrict entry events to having at least 1 observation period, a user defiend start date of December 31, 2011.'**
![image](https://user-images.githubusercontent.com/13936600/180438071-411d88da-da1a-4f0d-b23f-076993f8da81.png)

### Steps to reproduce behavior
See attached json
[json.txt](https://github.com/OHDSI/Atlas/files/9167673/json.txt)

**Comment by chrisknoll** [comment]
The inclusion rules relates to the cohort entry criteria, and when you say 'event starts between all days before and all days after', you are not actually restricting the event start date in any way which is why you don't see that being described in the print-friendly.

You're basically saying that the person in the entry event  has an observation period that can be user-defined to start at 2011-12-31, and the 2011-12-31 date can be any temporal proximity to the entry event's start date.

So the circe print friendly of : **Restrict entry events to having at least 1 observation period, a user defined start date of December 31, 2011.'** is what you're getting.
