### ISSUE TITLE
err:connection_refused

### ISSUE THREAD

**Issue by nzurawski** [OHDSI/Atlas#2742]
### Expected behavior
WebAPI to initialize without SSL and Atlas to load
### Actual behavior
Atlas can't connect to WebAPI with console errors of connection refused
### Steps to reproduce behavior
I've been trying to configure the security settings to enable SSL. After getting fully frustrated with it I went back to default security settings with security and SSL disabled. I have rebuilt the .WAR file and redeployed the WebAPI in Tomcat but when I load Atlas I get this error. I've attached screen shots of the error and my settings.xml file

Any help would be greatly appreciated

![conrefused](https://user-images.githubusercontent.com/111528072/187992128-ddb675f3-299a-425b-9b59-fed90a2bcf33.PNG)
![settings](https://user-images.githubusercontent.com/111528072/187992130-261bfcd0-0f0f-477e-8f28-cb97ec855e1e.PNG)

**Comment by chrisknoll** [comment]
what is your config-local.js file configured to point at?
An example is: 

```
define([], function () {
	var config = {};

	config.api =
		{
			name: 'Local',
			url: 'http://localhost:8080/WebAPI/'
		};
		config.userAuthenticationEnabled = false;
}
```

SSL configuration is different than security configuration in that in order to have SSL, you need certificates set up to receive encrypted HTTP requests.  There are a number of people who have set this up (I haven't done it recently) @anthonysena  do you have any guidance on this or @alex-odysseus ?

**Comment by nzurawski** [comment]
Closing as I've already figured this out with Anthony's help.
