### ISSUE TITLE
import a concept set to procedure type? 

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#275]
In ATLAS when defining procedure types it would be useful to be able to use a defined concept set rather than having to search for many of them individually. 

![image](https://cloud.githubusercontent.com/assets/11822115/20080038/9b47877a-a515-11e6-9d39-6ab88eeea7c5.png)
including @ericaVoss

**Comment by chrisknoll** [comment]
Certain elements work on a concept list notion: a concept set expression doesn't exactly make sense here because would you need to include descendants?  Would you need to excluded some child relationships?

The expected use case for this is that there'd be < 15 individual concepts, and the Import button would let you bulk add if you had a comma-delimited list of concepts.  Maybe we could improve the UI experience here, but concept set expressions isn't the right approach for this one.

**Comment by anthonysena** [comment]
Closing since @chrisknoll mentioned that this is the intended functionality and this issue is very stale.
