### ISSUE TITLE
2.12.0 missing node_modules

### ISSUE THREAD

**Issue by billsanto** [OHDSI/Atlas#2779]
### Expected behavior
$ls
build  docker  Dockerfile  images  index.html  js  LICENSE  node_modules  package.json  package-lock.json  README.md

### Actual behavior
$ls
build  docker  Dockerfile  images  index.html  js  LICENSE  package.json  README.md

### Steps to reproduce behavior
Unzip release. Navigate into archive. I couldn't find node_modules elsewhere in the archive. Was this overlooked?

**Comment by anthonysena** [comment]
Hi - you'll want to run `npm run build` as described here: https://github.com/OHDSI/Atlas/wiki/Atlas-Setup-Guide#code-deployment. We do not include the node_modules folder by design and this command will download and install the modules required. I'll close this out but please re-open if you are still facing an issue.

**Comment by billsanto** [comment]
Thanks @anthonysena
