### ISSUE TITLE
Notes and Devices data displayed in DataSources

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Atlas#284]
Achilles v1.4 contains new analyses for devices and notes.

These can be displayed in Atlas/DataSources

![image](https://cloud.githubusercontent.com/assets/7526119/20409096/4254ccee-ace6-11e6-9a13-ef1b7b68d2ab.png)

Do I need to also add JSON export for that? 
Or just a new webAPI function would be needed?

**Comment by t-abdul-basser** [comment]
As of current version of Atlas, one would export to JSON using Achilles and view the report in Atlas/Datasources.

**Comment by vojtechhuser** [comment]
I have not worked on the JSON export. I could use some help there. 
Although - is the JSON export our long term strategy? What is the 5 year vision besides JSON? I though webAPI enhancements... @t-abdul-basser

**Comment by t-abdul-basser** [comment]
Alright I will self-assign and add the export-2-JSON feature.

Yes, the ability to retrieve the reports from WebAPI rather than from mounted, exported JSON files is under development currently and is expected to be available in the next Atlas and WebAPI release. Once we have made this feature available in WebAPI and Atlas, I would expect that exporting to JSON in order to view the visualizations in Achilles Web/Atlas would cease to be our preferred approach and eventually might become a legacy feature.

**Comment by t-abdul-basser** [comment]
Retrieval of Achilles generated results via WebAPI and use of this capability in Atlas have been added to release candidates of WebAPI and Atlas respectively. Accordingly implementation of this feature *no longer* requires changes to Export to JSON functions in Achilles.
