### ISSUE TITLE
Show which concepts are descendants in included concepts tab

### ISSUE THREAD

**Issue by rmakadia** [OHDSI/Atlas#31]
After adding a concept and checking its descendants in a concept set, it would be nice to see which descendants belong to which concept. Thanks!

**Comment by anthonysena** [comment]
+1 to this

**Comment by pbr6cornell** [comment]
I like the idea, but I have no idea what the UI experience would look like to accomplish this task, since any concept could be descendant of multiple concepts in the conceptset.  This probably requires a UI design session to square away before any implementation takes place.

**Comment by rmakadia** [comment]
Agreed, its a more complex feature that would aid in how we choose and optimize concept sets

**Comment by pavgra** [comment]
@pbr6cornell, we've added a column, which shows id of concept (link), which brought current one into the concept set, and a tooltip, when you hover the id

**Comment by anthonysena** [comment]
Since I'm testing this out now, thought it would be helpful to post a few screenshots. Consider the following concept set definition:

![image](https://user-images.githubusercontent.com/12902366/38053785-0123fd1e-32a3-11e8-9020-5c661d366c4f.png)

The navigating the to the included concepts tab, you will see a new column labelled 'Ancestors' which will then list any/all ancestor concepts that are part of the concept set definition:

![cs-ancestor](https://user-images.githubusercontent.com/12902366/38053925-6998820c-32a3-11e8-8ac5-d66e98ee091d.png)

As Pavel mentioned, if you hover over the concept ID in the ancestor column, the tooltip will show you the concept name.

**Comment by pbr6cornell** [comment]
I think we need to have a community design session to figure out the best
way to represent the ancestor information.  I don't think the tabular
display will be ideal for all users, and I could imagine there could be
performance implications in always checking for ancestors.

**Comment by pavgra** [comment]
@pbr6cornell, then, what will be the action plan for this? Discuss at next Architecture call?

**Comment by anthonysena** [comment]
@pavgra sent an email to you and @gklebanov around this issue and a few others that would benefit from a discussion. Once we make some decisions, we'll post that up to the individual GitHub issues.

**Comment by pavgra** [comment]
I had a talk with @anthonysena and @fdefalco, who suggested following improvement of UI / UX side of things:

- Show just count of ancestor concepts for current one, not a list of id
- On hover: list their names
- On click: open modal with the list

So we'll rework the PR according to the ideas.

Also, Odysseus will work on performance of the feature, with a possible merge of two REST calls into single one. In long-term, we've discussed, it would be valuable to have back-end side pagination and filtering - that would give us definite profit in performance.

**Comment by pavgra** [comment]
@anthonysena , am I right that since https://github.com/OHDSI/Atlas/pull/614 and https://github.com/OHDSI/WebAPI/pull/369 were merged, we can close the issue?
