### ISSUE TITLE
Export multiple concept-sets - 

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Atlas#319]
Good day

"**Instructions:**Select the concept sets for export by selecting each row in the grid. When done, use the **_'Export Concept Sets'_** button which will start the download in a new window."

Looks like the **_'Export Concept Sets'_** button is missing - somehow

![export concept sets - button missing](https://cloud.githubusercontent.com/assets/13936600/22470721/2928f1da-e79e-11e6-81e5-a059f69ca632.png)

**Comment by anthonysena** [comment]
Hi - this is a bug with the button label but the export should still work. When you are in export mode (as shown in your screen shot), the label on the button that says "New Concept Set" should switch to say "Export Concept Sets". Unfortunately it does not in your build. 

Here is a work-around: if you click on "New Concept Set" while in this mode, it should then open a new window and export the selected concept set(s). 

I can confirm that this has been fixed in the upcoming build of Atlas so I'll tie this issue to that milestone and we'll close this out once it is released.
