### ISSUE TITLE
Cohort - Concept Selection

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#327]
As described in #196, the process for selecting concepts, such as condition types, is not intuitive. We need to devise a way to make this easier when constructing a cohort. 

Ideally, this experience should be "context aware". For example, if I reached the concept picker when attempting to load "condition type" concepts, the screen should immediately show these and allow for searching only within those condition types.

**Comment by chrisknoll** [comment]
There's a parameter to the concept picker which lets you specify the default domain. #196 had the problem because the default was 'Condition Concept Type' but that domain no longer exists.

In addition, the concept picker component has a 'default search' parameter that if you set it, it will initialize the list based on that search string.  This is good for cases where you know the search results is very small and you don't want to make users type in anything first (such as selecting a gender.

**Comment by anthonysena** [comment]
So as another step, we could also provide a means for filtering by domain and vocabulary in the existing concept picker as this would allow to resolve the "type" concepts as noted in #196.

It would be nice to use the same search experience here but I agree that this would require some design discussion. @fdefalco and I were thinking it through and it would require substantial changes to the search component.

**Comment by chrisknoll** [comment]
Yeah, that would be good, the concept picker component pre-dates the faceted data-table component, so it might be an idea to fold in the faceted data table into the concept picker so that you can quickly filter down to a desired subset.

**Comment by pbr6cornell** [comment]
A must for ATLAS 3.0 is to develop a consistent vocab search experience, which can be re-used whereever concepts (of any sort) are required to be selected, including in conceptsets and cohort definitions.

**Comment by anthonysena** [comment]
Closing due to age.
