### ISSUE TITLE
confirm method issue

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Atlas#36]
the confirm method is used in a few places to prompt the user and ensure they don't unintentionally navigate away and lose unsaved changes. If the user has checked the 'no longer allow this window to pop up messages' checkbox then the message is never displayed and call to confirm defaults to true.  

A different approach to the confirmation messages may need to be considered.

**Comment by anthonysena** [comment]
This SO article has some discussion on this problem: http://stackoverflow.com/questions/11261519/chrome-undo-the-action-of-prevent-this-page-from-creating-additional-dialogs. In summary, the answer is "close the tab and it will reset the settings for your site". 

We are using the confirm() method in a number of places to inform the user that they may lose their work. If the application raises > 1 confirm/alert messages, Chrome will then provide the user with the option to 'no longer allow this window to pop up messages'. Once selected, this will prevent additional confirm() messages AND it will also prevent the confirm from firing on the window.beforeunload event from firing properly. The window.beforeunload method is our last chance to prevent the user from losing work before closing their browser tab.

I'd propose we dedicate a modal dialog box at the page level of the application to provide this type of confirmation for in-app confirmation and reserve the use of the browser confirm() method for when a user attempts to close the browser tab (aka window object) so that this functionality is preserved.

**Comment by t-abdul-basser** [comment]
Seconded :)
