### ISSUE TITLE
Adding and Subtracting Concept Sets

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Atlas#366]
Enhancement Request

It would be great if we could build concept sets together.  

For example if we have a concept set for primary malignancy, one for secondary, and one for unspecified - I could mix and match them together.  For example sometimes I might need primary malignancy without unspecified and without lymphoma.  Essentially A - B - C.  It may seem like it would be easy to do with the definition, but it isn't always easy to piece them together.

**Comment by pbr6cornell** [comment]
Youve got that capability now in a conceptset with the compare function.

**Comment by pbr6cornell** [comment]
Youve got that capability now in a conceptset with the compare function.

On Feb 26, 2017 10:00 PM, "ericaVoss" <notifications@github.com> wrote:

Enhancement Request

It would be great if we could build concept sets together.

For example if we have a concept set for primary malignancy, one for
secondary, and one for unspecified - I could mix and match them together.
For example sometimes I might need primary malignancy without unspecified
and without lymphoma. Essentially A - B - C. It may seem like it would be
easy to do with the definition, but it isn't always easy to piece them
together.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/OHDSI/Atlas/issues/366>, or mute the thread

**Comment by ericaVoss** [comment]
awesome, I see the "Save New Concept Set from Selection Below" button.

That let's me add Concept A + B.

Now the wish is can I subtract a concept set, A + B - C.  Is there a way to do that that I"m not seeing?

**Comment by anthonysena** [comment]
It would take a few more steps but could be done with what we have today I believe. So using the compare function you could compare A and B to construct:

A + B -> Save to new Concept Set B'. I'd also consider using the 'Optimize' function on B' at that point.

Then do a compare of B' and C and you should be able to filter out the C concepts and create another concept set.

Would that work or did you have a different idea about how to work with concept sets A, B, C?
