### ISSUE TITLE
Duplicate instance of Atlas web app is launched 

### ISSUE THREAD

**Issue by mtadev** [OHDSI/Atlas#394]
### Expected behavior
The same instance of Atlas web app is utilized in any user session

### Actual behavior
A duplicate instance of Atlas web app is launched when selecting any member from a list of the cohort members matching Explore filters in effect (Explore tab, Cohort page)

### Steps to reproduce behavior
Invoke Atlas web app in a browser (URL http://www.ohdsi.org/web/atlas) -> 
Home page: select Cohorts from the main menu -> 
Cohorts page: select an existing cohort -> 
Cohort page: select Explore tab -> 
Explore tab: select a data source, then select a member from a list of the cohort members matching Explore filters in effect

Observe: 
A duplicate instance of Atlas web app is launched and switched to, and Profiles page is populated with the data for the selected cohort member.

**Comment by anthonysena** [comment]
Opening a new tab while exploring patient profiles from the cohort screen was a design decision. I believe this is the only area in Atlas that opens a new browser tab/window. In this instance I think that it makes sense since we're often exploring a patient profile and then using our findings to think about the cohort definition further. I'll close this for now but if you have a use case for keeping this in the same browser session, please add to the conversation. Thanks!
