### ISSUE TITLE
Atlas Inclusion Report - feature request - add distinct person or record

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Atlas#396]
- Applicable to Inclusion report - Attrition view and Intersect view.

### Expected behavior
- Label matches as either person or records. For record match, label: 'Record match', for person match, label" 'Person match'
- Provide count with and without distinct.
- See mockup attached.

### Actual behavior
- 'Match' does not clearly say if it is record matches or person matches. It is not clear if the N is person or record.
- Distinct people count is provided in final output, but not in attrition view or intersect view. 

### Steps to reproduce behavior
See: http://www.ohdsi.org/web/atlas/#/cohortdefinition/142003

![mockup](https://cloud.githubusercontent.com/assets/13936600/25524859/2ff9324c-2bda-11e7-9214-cfcb17bf4311.jpg)

**Comment by chrisknoll** [comment]
It is always 'records' (or as I refer to them: events), and we don't go back to the cohort definition in this report to determine if the user picked 'earliest event per person' and alter the labeling to say 'person' because we can infer that the number represents distinct people due to the 'one event per person' definition.  It made it a bit complicated (there are numerous ways of limiting the events to 1 per person, by cohort definition 'limits' or using logical criteria that would also limit to one event per person'. 

So where it is left is that the person needs to understand the definition in order to interpret the number as either 'this is the number of times people entered the cohort (events)' vs. 'this is the number of people in the cohort (by nature of a person could only enter the cohort one time).

**Comment by gowthamrao** [comment]
Thank you @chrisknoll  for clarifying Record vs Person. That makes sense.

But how about second feature request 'Distinct N' in addition to N - as in screen shot. I know it is invaluable, because N/Distinct N gives records per person.

**Comment by gowthamrao** [comment]
@chrisknoll 

see example http://www.ohdsi.org/web/atlas/#/cohortdefinition/1747823

**Current attrition view shows attrition of records**
![image](https://user-images.githubusercontent.com/13936600/38884899-1170784a-423f-11e8-8be0-f32ff7151d5b.png)

Would prefer to have attrition of both subject_id and records

![image](https://user-images.githubusercontent.com/13936600/38884982-5da9d710-423f-11e8-8db8-d5822f7c1da1.png)


Is this possible to do by doing something like count(distinct subject_id) as Subjects, count(*) as Records

**Comment by gowthamrao** [comment]
@chrisknoll sorry to keep bringing this up, but is this possible

See this cohort definition http://www.ohdsi.org/web/atlas/#/cohortdefinition/1769011
It uses all eligible visits as the initial event, and then applies inclusion criteria. The attrition view provides attrition of records, not attrition of person_id's.
![image](https://user-images.githubusercontent.com/13936600/39966978-3d351484-5682-11e8-9915-564ae77d4f64.png)

What we also need is, attrition of unique person_id's in addition to attrition of records. Ofcourse, if we had selected 'earliest event' or 'latest event' - then attrition of records would be equal to attrition of person_id's, but in this example that is not the case.

**Comment by chrisknoll** [comment]
Yes, I'm actively working on a solution for this.

**Comment by anthonysena** [comment]
@chrisknoll for this one, is it still an issue? I see the closed PR and believe we have the by person/by event tabs now?

**Comment by chrisknoll** [comment]
No, this is resolved. There is a Report By Person and By Event view for the inclusion rule report.
