### ISSUE TITLE
Unable to delete cohort

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/Atlas#430]
### Expected behavior
Using epi.jnj.com - select delete button for a cohort, select OK button on pop up window, cohort is then deleted. 
### Actual behavior
Cohort is not deleted.
### Steps to reproduce behavior
select delete button for a cohort, select OK button on pop up window, close cohort, go to cohort directory and search for cohort that was supposed to be deleted. 
Cohorts that failed to be deleted: 4467 and 4466.

**Comment by chrisknoll** [comment]
Hi, @jhardin29 , this was a patch to our internal environment to make a workaround for the WebAPI issue OHDSI/WebAPI#219 and not made to the git repo (so there is no fix to be made here). The PR OHDSI/WebAPI#220 gives us the performance benefit that we fixed in 219 without the bug you've identified here. 

I'll be pushing the latest WebAPI release to our internal environment tonight, and I'll let you know when you can try to delete.
