### ISSUE TITLE
BadSqlGrammarException when generating cohorts

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Atlas#437]
### Expected behavior
Cohort generator by cohort builder in Atlas version 2.1.0, WebAPI version 2.1.0

### Actual behavior
FAILURE. 
Looking at the batch_step_execution for cohortDefinition.generateCohort I see a ...jdbc.BadSqlGrammarException

### Steps to reproduce behavior
Happens here with every cohort.

Any ideas how to further debug this? 

I tried to run the postgresql query generated in Export tab and this runs just fine??
All necessary results tables are added for the multi-database setup.

Thanks

**Comment by chrisknoll** [comment]
The export tab doesn't contain the part of the code that generates the statistics, which is found here:
https://github.com/OHDSI/WebAPI/blob/master/src/main/resources/resources/cohortdefinition/sql/generateCohort.sql#L71

so you should add that part of the code to the exported SQL to see if it has an error. This code was recently changed to address OHDSI/WebAPI#215.  The specific change was to do perform a cross join to calculate the total people in cohort together with the total people who matched all criteria:

```sql
-- calculate totals
delete from @results_database_schema.cohort_summary_stats where cohort_definition_id = @target_cohort_id;
insert into @results_database_schema.cohort_summary_stats (cohort_definition_id, base_count, final_count)
select @target_cohort_id as cohort_definition_id, PC.total as person_count, coalesce(FC.total, 0) as final_count
FROM
(select count(event_id) as total from #qualified_events) PC,
(select sum(sr.person_count) as total
  from @results_database_schema.cohort_inclusion_result sr
  CROSS JOIN (select count(*) as total_rules from @results_database_schema.cohort_inclusion where cohort_definition_id = @target_cohort_id) RuleTotal
  where cohort_definition_id = @target_cohort_id and sr.inclusion_rule_mask = POWER(cast(2 as bigint),RuleTotal.total_rules)-1
) FC
```

To get this to work, you may need to do a sort of 'manual sql translation' because of the default sql syntax, but my guess is that there's something inside this generate statistics part of the query that is not running.

If i needed to debug this directly, I'll need to get a postgresql instance with the CDM tables on it to try to generate the cohort. I believe we have an OHDSI postgresql env to try this out on so I can see if I can uncover any errors if you can't identify the bad sql.

-Chris

**Comment by PRijnbeek** [comment]
Hi Chris,

I am trying to use SqlRender to translate this to PostGres. I do see some things the generateCohort.sql i do not fully understand. The things like @strategyInserts, @censoringInserts, what are those? These are no parameters right? 

That query reads the cohort definition from the CDM i see do i should be able to run this with the necessary parameters through sqlRender correct?

**Comment by chrisknoll** [comment]
Hi, @PRijnbeek , 
  @strategyinserts and @censoringinserts will be injected into the query if you specify an end date strategy (such as a fixed offset from the cohort end date) or if you specified censoring events in the cohort definition, it will find those events and use them as cohort end dates.  You probably didn't specify either of these things, so the @strategyinserts and @censoringinserts will be replaced with an empty string.

To figure out where your sql error is, I'm suggesting that you take the generated SQL you got from Atlas (that worked) and insert this SQL into the statement before the final temp table cleanup:

```sql
-- calculte matching group counts
delete from @results_database_schema.cohort_inclusion_result where cohort_definition_id = @target_cohort_id;
insert into @results_database_schema.cohort_inclusion_result (cohort_definition_id, inclusion_rule_mask, person_count)
select @target_cohort_id as cohort_definition_id, inclusion_rule_mask, count(*) as person_count
from
(
  select Q.person_id, Q.event_id, CAST(SUM(coalesce(POWER(cast(2 as bigint), I.inclusion_rule_id), 0)) AS bigint) as inclusion_rule_mask
  from #qualified_events Q
  LEFT JOIN #inclusionRuleCohorts I on q.person_id = i.person_id and q.event_id = i.event_id
  GROUP BY Q.person_id, Q.event_id
) MG -- matching groups
group by inclusion_rule_mask
;

-- calculate gain counts
delete from @results_database_schema.cohort_inclusion_stats where cohort_definition_id = @target_cohort_id;
insert into @results_database_schema.cohort_inclusion_stats (cohort_definition_id, rule_sequence, person_count, gain_count, person_total)
select ir.cohort_definition_id, ir.rule_sequence, coalesce(T.person_count, 0) as person_count, coalesce(SR.person_count, 0) gain_count, EventTotal.total
from @results_database_schema.cohort_inclusion ir
left join
(
  select i.inclusion_rule_id, count(i.event_id) as person_count
  from #qualified_events Q
  JOIN #inclusionRuleCohorts i on Q.person_id = I.person_id and Q.event_id = i.event_id
  group by i.inclusion_rule_id
) T on ir.rule_sequence = T.inclusion_rule_id
CROSS JOIN (select count(*) as total_rules from @results_database_schema.cohort_inclusion where cohort_definition_id = @target_cohort_id) RuleTotal
CROSS JOIN (select count(event_id) as total from #qualified_events) EventTotal
LEFT JOIN @results_database_schema.cohort_inclusion_result SR on SR.cohort_definition_id = @target_cohort_id AND (POWER(cast(2 as bigint),RuleTotal.total_rules) - POWER(cast(2 as bigint),ir.rule_sequence) - 1) = SR.inclusion_rule_mask -- POWER(2,rule count) - POWER(2,rule sequence) - 1 is the mask for 'all except this rule' 
WHERE ir.cohort_definition_id = @target_cohort_id
;

-- calculate totals
delete from @results_database_schema.cohort_summary_stats where cohort_definition_id = @target_cohort_id;
insert into @results_database_schema.cohort_summary_stats (cohort_definition_id, base_count, final_count)
select @target_cohort_id as cohort_definition_id, PC.total as person_count, coalesce(FC.total, 0) as final_count
FROM
(select count(event_id) as total from #qualified_events) PC,
(select sum(sr.person_count) as total
  from @results_database_schema.cohort_inclusion_result sr
  CROSS JOIN (select count(*) as total_rules from @results_database_schema.cohort_inclusion where cohort_definition_id = @target_cohort_id) RuleTotal
  where cohort_definition_id = @target_cohort_id and sr.inclusion_rule_mask = POWER(cast(2 as bigint),RuleTotal.total_rules)-1
) FC
;
```

Put this code right before the truncate/drops:

```sql
TRUNCATE TABLE #cohort_ends;
DROP TABLE #cohort_ends;

TRUNCATE TABLE #inclusionRuleCohorts;
DROP TABLE #inclusionRuleCohorts;
```

-Chris

**Comment by PRijnbeek** [comment]
@chrisknoll 
I ran the additional counting code and the issue was that there was no cohort_summary_stats table in the schema for the multi-database setup. This one was also not mentioned on [this page](http://www.ohdsi.org/web/wiki/doku.php?id=documentation:software:webapi:multiple_datasets_configuration) to instantiate. 

Looking at this table again i think there may be more tables missing for the multi-database setup. I think the cohort table is now also in the results schema correct instead of the CDM schema (which indeed makes sense since it is derived data)?

I wonder if we can make it easier for users to also provide the necessary tables in a DDL per DBMS like the CDM tables for each CDM release that you need to run in each results schema. We can then link to this on the multi-database setup page. This is a lot easier than manually copying each ddl. I will add this suggestion to the recent forum post about this topic by @gowthamrao: http://forums.ohdsi.org/t/ohdsi-tables-architecture-deploying-on-multiple-dbms-platforms/3481

**Comment by PRijnbeek** [comment]
If I run with the new Feature Generation i do have the same problem.

I added heracles_visualization_data which was not in the table to instantiate but are there maybe more tables I need to add to make this work?

@Chris can you point me to the code that is run in this case to see where the problem is?

**Comment by chrisknoll** [comment]
@PRijnbeek ,
 I've updated the wiki page with the latest list of tables that should be inserted into the results schema.  I've added the tables for the feature extraction results, as well as the row for the 'cohort' table.  Note on the cohort table:  it's always been considered a separate table from the cdm.cohort table due to that certain sites lock down their cdm schema to be read only.  It's just unfortunate that we used the same table name in the results schema, so this leads to a lot of confusion. But the cohort generation in WebAPI writes to the results schema only, which is why we created a cohort table in the results schema.

You can find the DDL for the feature results here:
https://github.com/OHDSI/WebAPI/blob/master/src/main/resources/db/migration/sqlserver/V1.0.8.0__cohort_features_results.sql

As far as providing DDL for the results schema:
The problem is that between releases, tables may need to be altered that you can't work off a 'create' ddl if you already have existing tables.  This is why we have systems like Flyway to manage this migration, but it's not set up to handle our results schema, so we risk having problems like this.  
Example of a migration script that alters and updates:

```
ALTER TABLE [${ohdsiSchema}].cohort_generation_info
	ADD include_features bit,
		fail_message varchar(2000),
		person_count bigint,
		record_count bigint
GO

UPDATE [${ohdsiSchema}].cohort_generation_info set include_features = 0
GO

ALTER TABLE [${ohdsiSchema}].cohort_generation_info
	ALTER COLUMN include_features bit not null
GO
```

This script was automatically applied to the WebAPI's ohdsi schema and didn't require any extra steps for you.  I'd prefer it if all our database migrations were handled this way.

Another challenge is the number of DDL scripts we'll need to maintain:  our main platforms we support for WebAPI is oracle, sqlserver, postgresql. ..so it's painful (but manageable) to maintain 3 sets of migration scripts for WebAPI.  But once we provide DDL for the results schema, the platforms expand to pdw, redshift, impala, netiza, and bigquery. But with enough community involvement, we might have enough support to maintain this.

**Comment by PRijnbeek** [comment]
Thanks Chris. Cohort Features now works.

What would be the perfect solution for me i think is if I can make a WebAPI call with parameters to specify the database and results schema. WebAPI could then populate/migrate the tables like it does now nicely for the WebAPI's ohdsi schema. This would make all the DDL scripts unnecessary as I understand this is a workload. But maybe there are good reasons why this is not possible..?

**Comment by chrisknoll** [comment]
The main problem is that the migration framework (flyway) wants to store the current migration state in a table stored on the database: schema_version.  The framework uses inserts like getTime() and other features that aren't supported by MPP systems (like pdw, redshift, bigquery, etc).  So this is just a limitation of the framework, but it's inescapable that something needs to keep track of which tables have been migrated (you can't just re-migrate tables every time webapi starts up).  

If there was some alternative migration framework that would store the migration status in a flat-file or something like that, it would work.  If we had something like that, we could manage results_schema migrations using that framework and leave the webAPI schema maintained by flyway.

**Comment by PRijnbeek** [comment]
Thanks for the explanation. 

For now I created a createResultsTables.sql script for Postgresql that I can use when i need to add a new version of the database. I will need to update that if new tables are needed as was the case now. It would be good to have that information as part of a release in the future.

**Comment by chrisknoll** [comment]
Agreed, @PRijnbeek , it was a complete miss on my part to not have the wiki documentation updated and it called out in the release notes.

In the case where we have a dialect-specific DDL for the results schema, how do you think we could handle cases where tables are altered? Do we always go with a drop-create and lose existing data?
