### ISSUE TITLE
Cohort Generation SQL not pointing to Vocab Schema correctly

### ISSUE THREAD

**Issue by jduke99** [OHDSI/Atlas#453]
### Expected behavior
Generated sql should point to the Vocabulary schema as defined in the DAIMON table

### Actual behavior
The cohort generation script is using @cdm_database_schema instead of my vocabulary schema, thus is cannot find the concept table.

INSERT INTO #Codesets (codeset_id, concept_id)
SELECT 0 as codeset_id, c.concept_id FROM (select distinct I.concept_id FROM
( 
  select concept_id from @cdm_database_schema.CONCEPT where concept_id in (312648,44834715,320128,44833556,44823109,44821949)and invalid_reason is null
UNION  select c.concept_id
  from @cdm_database_schema.CONCEPT c
  join @cdm_database_schema.CONCEPT_ANCESTOR ca on c.concept_id = ca.descendant_concept_id
  and ca.ancestor_concept_id in (44834715,320128,44833556,44823109,44821949)
  and c.invalid_reason is null
UNION
select distinct cr.concept_id_1 as concept_id
FROM

### Steps to reproduce behavior
Try to generate a cohort in an environment where the cdm schema and vocab schema are not the same.

**Comment by pbr6cornell** [comment]
cdm schema must contain vocabulary.

On Sep 1, 2017 5:10 PM, "Jon Duke" <notifications@github.com> wrote:

Expected behavior

Generated sql should point to the Vocabulary schema as defined in the
DAIMON table
Actual behavior

The cohort generation script is using @cdm_database_schema instead of my
vocabulary schema, thus is cannot find the concept table.

INSERT INTO #Codesets (codeset_id, concept_id)
SELECT 0 as codeset_id, c.concept_id FROM (select distinct I.concept_id FROM
(
select concept_id from @cdm_database_schema.CONCEPT where concept_id in
(312648,44834715,320128,44833556,44823109,44821949)and invalid_reason is
null
UNION select c.concept_id
from @cdm_database_schema.CONCEPT c
join @cdm_database_schema.CONCEPT_ANCESTOR ca on c.concept_id =
ca.descendant_concept_id
and ca.ancestor_concept_id in (44834715,320128,44833556,44823109,44821949)
and c.invalid_reason is null
UNION
select distinct cr.concept_id_1 as concept_id
FROM
Steps to reproduce behavior

Try to generate a cohort in an environment where the cdm schema and vocab
schema are not the same.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/OHDSI/Atlas/issues/453>, or mute the thread

**Comment by chrisknoll** [comment]
To void copying a vocabulary to multiple CDM schemas in the same instance, you can create a view to point to a single set of instantiated vocabulary tables and put it into the CDM schema table.  Refreshing the concrete vocabulary tables will automatically propagate through to the views.

**Comment by jduke99** [comment]
Thanks Chris and Patrick.  But then why have a vocab schema option in the Daimon table?

**Comment by pbr6cornell** [comment]
for doing vocabulary search, which is not data dependent.
