### ISSUE TITLE
Enhancement request - ability to move concept sets back into main repository

### ISSUE THREAD

**Issue by rmakadia** [OHDSI/Atlas#499]

**Comment by pbr6cornell** [comment]
Currently, we have import capabilities from the conceptset library into a cohort, but not export capabilities from a cohort definition to the conceptset library.  I agree that would be a nice addition, because sometimes I find myself iterating on a conceptset in the context of a cohort, and i have to copy/paste it into the conceptset library once i like it.  I don't know how to handle the 'overwriting' issue, though I suspect we need exports to be unique entities and not try to deal with versioning (at least not as an initial approach).

**Comment by anthonysena** [comment]
Hi - we have a PR open to address this issue #634 and we made some decisions to limit the scope of the functionality. We decided to allow a user to copy a concept set back to the repository but they cannot overwrite an existing concept set. When copying the concept set back to the repository, we'll enforce a unique name so that there are no naming collisions.
