### ISSUE TITLE
Generation Tab - Intra-Window Scrolling

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Atlas#507]
### Expected behavior
See all CDM Sources on Generation Tab without scrolling

### Actual behavior
iFrame window thingy requires scrolling (I know it isn't an iFrame but that is what it reminds me of).

Is it possible to remove the intra-window scrolling on the Generation tab?  It makes it harder to quickly maneuver around and generate.

**Comment by alondhe** [comment]
This div is constrained to allow for the reporting tools (feature generation, inclusion rule reports) to reside below, but perhaps those can be shown in modals instead?

**Comment by chrisknoll** [comment]
Would anyone like the idea where you click a 'generate' button at the top, it pulls up a modal with all the available data sources, and only those sources that are run appear on the generate screen?  Any prior-run datasources that appear there can also have a 'regenerate' button to let you generate directly on a source without going through the modal?  Similar to the genreate experience under the Incidence Rate tool, but isntead of sources being displayed in  a dropdown, it would be a button->modal user experience instead of dropdowns.

**Comment by t-abdul-basser** [comment]
@chrisknoll This sounds like an improved user experience.

**Comment by alondhe** [comment]
@chrisknoll I like this as well, but one enhancement to the dropdown of "regenerate" options -- can it do multi-select? In the IR tool currently, doesn't look like that is available.

**Comment by chrisknoll** [comment]
instead of buttons we could have checks to click on each, it almost amounts to the same thing, unless there's a 'select all' option and then you click generate and it will regen all the checked sources...maybe that would work?

**Comment by fdefalco** [comment]
Ah, memories... We started a discussion on this over a year ago and never quite made it to the design phase.  Could we potentially come up with a few designs, share them for feedback and get to a consensus on a UI?

http://forums.ohdsi.org/t/a-unified-generation/1792

**Comment by chrisknoll** [comment]
You should probably try to revive that thread, it's not exactly clear what the next steps were.

In the meantime, I can work on a functional mockup on a separate branch to get some internal comments and review before sharing with a broader audience.

**Comment by anthonysena** [comment]
Closing this out and linking to #1882 which proposes to use the generation experience from the incidence rate module for all generation in ATLAS.
