### ISSUE TITLE
Searching Source Codes

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Atlas#510]
### Expected behavior
I search source codes and I can filter by Vocabulary

### Actual behavior
Atlas searches all source codes

### Steps to reproduce behavior

1. Go to ATLAS
2. Go to "Vocabulary" and then "Import" tab
3. Select "Source Codes" option
4. Search for source codes

Some source codes are non-unique across vocabularies so being able to assert the Vocabulary you are searching would be helpful.

Thank you to David Myers for identifying this enhancement.

**Comment by fdefalco** [comment]
I'm not clear on what you are looking for on this issue.  

When you go to the Vocabulary, Import, Source Codes tab you are importing a list of source codes.  When you import a list of source codes the source codes that are returned in the table have a filter for vocabulary on the left.  You could use that filter and then uncheck any source codes that are from a vocabulary you didn't want but were returned because they matched your import list.  

Are you suggesting that when you import you have an option to specify a limited number of vocabularies to search?

Also, could you provide a list of source codes you are using that could be used as a test case?

**Comment by fdefalco** [comment]
met with erica and resolve in new import.
