### ISSUE TITLE
How to access backend WebAPI locally over internet

### ISSUE THREAD

**Issue by sajagekar** [OHDSI/Atlas#534]
We have Atlas deployed on Tomcat8 and WebAPI using spring-boot. We have configured url as below in config.js, But while accessing over the internet it is trying to search for localhost application. How to configure proxy url here?

Note- Here, I don't want to hard code the url of back end. Because we don't want to open ports for back-end applications (Security reasons).

// default configuration
	config.api = {
		name: 'Local',
		url: 'http://localhost:9080/WebAPI/'
	};

**Comment by MaximMoinat** [comment]
Are you sure the port `9080` is correct? By default the WebAPI will be deployed at port `8080`.

Please share your WebAPI settings (found in the `pom.xml` and/or `settings.xml`) if this does not solve your problem.

**Comment by sajagekar** [comment]
Yes, The port is correct 9080 and the application is running when we specify IP address.

But when we specify localhost and try to open url from other machine then it searches for localhost on that PC. Instead it should search for http://{dns_name}/WebAPI/..., or should redirect to app where it has deployed.

After searching on internet it seems related to proxy setting. So how we can achieve this in Atlas UI?
e.g below is the example for angular app
https://stackoverflow.com/questions/46451200/angular-2-localhost-and-backendserver-connection
Is there any way to do this in knockout.js or in Atlas project?

**Comment by anthonysena** [comment]
Hi @sajagekar - I'd recommend that you add a file 'config-local.js' to your Atlas installation as described on the wiki:

http://www.ohdsi.org/web/wiki/doku.php?id=documentation:software:atlas:setup

This will allow you to override the config.js settings to specify the URL to your WebAPI installation. Let me know if this is answers your question.

**Comment by sajagekar** [comment]
I will add config-local.js and will check if it works with localhost url. 

@anthonysena - How do you deploy it on linux machine (servers etc) and access it over the internet from other machine (windows)? Doesn't it searches for localhost? Provided WebAPI project should not be exposed over the internet.

**Comment by anthonysena** [comment]
@sajagekar - to confirm: you have successfully deployed Atlas/WebAPI and are able to access it on the server where it is hosted using localhost? And you are asking how to then access it from another machine on the same network and/or the internet? In order to do this, both Atlas and WebAPI need to be exposed to clients in order to function.

One option is to find the IP address of your server and use it in your config-local.js for WebAPI so that the URL looks like: `http://<your server ip here>/WebAPI`. Then from another machine that is on the same network attempt to connect to Atlas via `http://<your server ip here>/atlas`. 

WebAPI can be further secured so that it only accepts requests from your client application. See the installation guide here:

http://www.ohdsi.org/web/wiki/doku.php?id=documentation:software:webapi:webapi_installation_guide

The <security.origin> setting will allow you to accept requests from specific applications. More details are described here:

http://www.ohdsi.org/web/wiki/doku.php?id=development:security

Let me know if this is helpful.

**Comment by sajagekar** [comment]
@MaximMoinat & @anthonysena - Thanks for your immediate replies.
I have solved this by configuring reverse proxy.
Used Apache httpd web server (Apache2) for UI deployment.
and changed url to only "/WebAPI" inside local config.
configured as- 
ProxyPass "/WebAPI" "http://localhost/WebAPI"
ProxyPassReverse "/WebAPI" "http://localhost/WebAPI"

source-https://httpd.apache.org/docs/2.4/mod/mod_proxy.html

**Comment by t-abdul-basser** [comment]
Glad that found a solution. We do the same here with _nginx_.
