### ISSUE TITLE
OHDSI concept set creation malfunction

### ISSUE THREAD

**Issue by chantekhani89** [OHDSI/Atlas#562]
For some reason, I am not able to create concept sets in Atlas. Whenever I try to save a concept set, I get an error screen that says "An error occurred while attempting to find a concept set with the name you provided."  As far as I can tell, this has been going for at least 48 hours.  What can be done to correct this?

**Comment by chrisknoll** [comment]
This URL will produce an internal server error (which is supposed to check the existence of a concept set name: http://api.ohdsi.org/WebAPI/conceptset/exists?name=test%20concept%20set

It appears to be returning a number format exception, but I'm not sure where a number is being parsed.  I'll follow the stack trace to where we make the call.

**Comment by chrisknoll** [comment]
Ok, so based on my examination, the URL being sent to the server from Atlas on ohdsi.org is the form:
/conceptset/exists?name=blah.  However, the current release of webAPI expects the form conceptset/{id}/exists/name. This is where the number format exception is comming from.

However, I'm looking at the current release of Atlas (based on the released tag) and it's not pointing to the actual latest version of the relase (it's actually a few commits ahead), so I think the fix is to re-associate the release with v2.2.1 tag, and that should address the issue.  I'll try that.

**Comment by chantekhani89** [comment]
Thank you so much for working on this, I am so grateful!

Chante

**Comment by chrisknoll** [comment]
The release on ohdsi.org has been updated to point to the correct release.  I've verified I am able to create concept sets.
