### ISSUE TITLE
User Interface for Daimon / Source Configuration

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Atlas#57]
As per @leeevans

**Comment by pavgra** [comment]
@fdefalco, @leeevans, we' like to work on the enhancement, so here is our design proposal:

- The configuration is available only when Atlas is running in secured mode (auth enabled)
- We add "New data source" button, which will display modal window with form for data source creation
- We add a column at right, where Edit icon / button will be displayed. It will open the form, prefilled with the DS connection details, for edit
- Since there is caching enabled on Atlas startup, there will be a need to restart Atlas, so such button is also required

**Comment by leeevans** [comment]
@pavgra sounds good, I'm looking forward to being able to use this feature!

I would suggest that the source jdbc connection string should be entered as a single string (no attempt to break it out into component pieces like host, database etc) for simplicity. That also allows any additional connection parameters to be easily included by the user if needed.

It would also be useful to show some help text for the user with literal examples of jdbc connection string formats for the OHDSI supported DBMSs.

**Comment by pavgra** [comment]
@leeevans, I absolutely agree with you regarding jdbc connection as simple string. We've tried to create a jdbc links builder in Arachne, but there were so much options coming from all DB vendors, that we've ended up exactly with plain input.

**Comment by anthonysena** [comment]
@pavgra This sounds good and could also encompass the functionality that is in this PR: https://github.com/OHDSI/Atlas/pull/541. In that PR, we discussed the need to have a "settings" screen for Atlas users that allows them to review the data sources and to control which data sources are used to report counts for concepts on a per-user session basis. This would be separate from a "configuration" screen that allows for administration of data sources and in the case of #541 the daimon priorities across the Atlas instance.

**Comment by pavgra** [comment]
@anthonysena, I would better add a selector (dropdown / popup / whatever) for admins, which allow them to choose, whether they are changing daimon priority for their current session only or for the whole app in general. Creating quite identical page for just administration purposes, from my point, seems a bit redundant.

**Comment by anthonysena** [comment]
@pavgra Sounds like a good approach to me. Thank you!
