### ISSUE TITLE
Clean and reasonable project structure

### ISSUE THREAD

**Issue by pavgra** [OHDSI/Atlas#633]
Today files in the project are quite messed up and it would be good to define strict project structure, simplifying code navigation.

Proposal is following:
1) "components" folder for shared (maximally stateless) UI things
1) "pages" / "modules" folder for app's pages stored in hierarchical way, presenting app's structure
1) use relative paths when it possible, or absolute ones across app. and create aliases in config file only for external libs
1) CSS should be written in granular way. A file per template
1) All API calls should be accumulated in "services" folder, no inlined AJAX calls or utility code blocks should take place in controllers

Naming is a subject for discussion.

Changes required to align current codebase to the described structure are going to be done in separate branch. Also the defined structure should be put into README and forced for usage during code-reviews.

@chrisknoll, @fdefalco, @anthonysena , would be grateful to receive your opinion on this.

**Comment by chrisknoll** [comment]
I think these are great ideas and will support them in any way I can.

**Comment by fdefalco** [comment]
I'm in support of these suggestions but think they should be done after the 2.4 release.

**Comment by t-abdul-basser** [comment]
@pavgra This would be very helpful refactoring effort. I agree with @fdefalco that they should be pushed to post v2.4 release though.

**Comment by anthonysena** [comment]
Making a note that we should also include the module cleanup that @chrisknoll proposed as part of #611.

**Comment by Sigfried** [comment]
Maybe this is the right place to ask: Is anyone is considering getting away from requirejs anytime soon?

I'm back to working on ATLAS and I want to use libraries written with ES6 imports. I think I can get stuff like that working with something like https://github.com/mikach/requirejs-babel, but if we might be moving toward ES6 module imports, there's no sense messing with temporary bridging kludges.

Has this been discussed lately?

**Comment by chrisknoll** [comment]
Let's focus this discussion on project structure.  It doesn't matter what the module syntax is for us to clean up and address @pavgra items, and we wouldn't want to be distracted by a holy-war over module systems.

If you do want to discuss it, I think opening up a separate issue on this or starting a forum discussion on it.

> I'm back to working on ATLAS and I want to use libraries written with ES6 imports.
You can do this, just use the bundled library (via CDN or otherwise). We do this with d3, so use that as an example.

**Comment by Sigfried** [comment]
No problem. Here it is: https://github.com/OHDSI/Atlas/issues/654

**Comment by chrisknoll** [comment]
Hi @johnSamilin 

Thanks for drafting this up.  A few thoughts:  
1. I like the structure of routes.  It makes sense that each sub-page would define it's own set of routes.  Good!

2. Everything is under /pages:  we're going to have components that aren't pages themselves, so I don't think we'd put everything under /pages.  We should probably have a root folder for pages, another folder for components, and the components under /pages will leverage the stand-alone components found in /components

3. One-folder-per-module:  This is set up like a webpack project where you expect to be able to load a module via "pages/data-sources/reports/dashboard", but this isn't' web-pack, and every module reference must resolve to a file, not a folder, so to load that module you'd have to use "pages/data-sources/reports/dashboard/dashboard", which is awkward.  I like how the components under 'charts' is structured, but I'm a little confused bout that case because wasn't our charts exported to an external library? So I don't know why those files are shown here...except I like the arrangement of those files vs. the ones under the other report sections.

With the last 2 points in mind, I've put together 2 options I'd like you to consider.

### Option 1: one module per file, separate folders for template and stylesheets:

![option1](https://user-images.githubusercontent.com/6818777/39959224-bdfc6852-55dc-11e8-8857-a6728ef20c3a.png)

In this option, I'm putting components and pages in separate root folders.  Pages will contain all the components specifically for driving the Atlas pages.  components will be where we place the re-usable elements of the application.Note: I'm putting charts and reports under /components because they should be reusable things, and not specific to any one page...For example: the person report should be the same report for data sources and cohort characterization.  I also have separate folders for templates and stylesheets to tuck those assets away from the main folder with the modules.  To reference those assets, in the module define, you would do this:

```
define(['text!./templates/dashboard.html', 'less!./stylesheet/dashboard.less'], function (template) {...});
```

I propose this option so that you can look at the directory structure and clearly see what components are defined.

### Option 2: one module per file, do not have separate folders for styleshets/templates

![option2](https://user-images.githubusercontent.com/6818777/39959295-76f0022e-55dd-11e8-8a83-03ce5e86c39d.png)

This folder structure is nearly identical to option 1 (from a top-level folder organization), but instead of sub-folders for stylesheet and template assets, they are now in the main folder for the component, and if we adhere to some naming conventions, the assets will be grouped together.  In this way, the external assets are imported via:

```
define(['text!./dashboard.html', 'less!./dashboard.less'], function (template) {...});
```

### Module ID resolution

With this folder structure, instead of this:

```
// some page module
define(['pages/data-sources/components/reports/dashboard/dashboard'], function () { } );
```

It is this:
```
// some page module
define(['components/reports/dashboard'], function () { } );
```

If we do feel like we should have sub-groups of reports, we could put that into a sub-group:
```
// some page module
define(['components/reports/data-sources/dashboard'], function () { } );
```

But I still think that we should think of reports as more atomic things that aren't tied to one specific function in the application.

-Chris

**Comment by pavgra** [comment]
@chrisknoll , I believe that the first option, which is structuring by content type, doesn't work good for big projects, especially when we do not have strict typification.

The second option looks quite similar to what was proposed in the branch, but I would combine it with the @johnSamilin 's approach:
- there are common components used all across the app, and of course, it is reasonable to store them in top-level components folder
- there are components, which are specific to some page (or a group of pages) and as for me, it sounds logical to put them into folder nested in the page's one. Otherwise, the top-level components folder will grow much faster and separation by modules (pages / group of pages) would not be so clear and obvious. In other words, if we have a page and all its dependencies in a single folder, we could easily modularize it, and it would enforce loose coupling of js code blocks.

**Comment by johnSamilin** [comment]
@chrisknoll, thanks for the review,
as for module IDs - we could rename `components/dashboard/dashboard.js` to `components/dashboard/main.js` and thus get rid of the repetition and save the folder structure. This will make errors in console less informative though helps you stay focused when you work on a component

**Comment by chrisknoll** [comment]
Hi, @johnSamilin ,
  I don't think this is a viable approach.  If i'm working on multiple modules (which happens often), all of my open files will all be 'main.js'?  That doesn't sound reasonable.

I feel what's happening here is that we're trying to make this all look like a node or webpack project structure, and we're using AMD formatted modules.  In AMD world, it's one module per file (vs. one module per folder).   So, since we're in the world of AMD, let's follow the model that modules resolve to a single file, and work under those rules.  I think we should consider folders as 'collections of modules' (or like a java 'package').

@pavgra, I understand your point about folder specific content types (when I suggested a stylesheets and templates folder) instead, maybe we have a more generic 'resource' or 'etc' or something else that we can place all those separate assets into (if we have an objection to having the resources co-mingled with the module files).

**Comment by pavgra** [comment]
@chrisknoll , if the resource (under resource I assume stylesheet) is component specific, why should we move it far from the component? It should be tightly coupled with the component's controller and template, so should be near

**Comment by chrisknoll** [comment]
I'm thinking that resources might be shared across components (ie, an image for an icon or something like that).  But my Option 2 above grouped those assets all in the same package folder so I'm fine with keeping them with the component, but remember: we'll have multiple components in a single folder, not one folder per component.

**Comment by pavgra** [comment]
Icons and similar resources - yes, no objections. I was talking about stylesheets.

So, all in all, do we agree on the following change list for the PR?
- move components, which are common for multiple modules into shared top-level "components" folder
- have top-level and module-level "resources" folders for images and similar assets
- flatten folders to exclude requires like "some-component/some-component"

@chrisknoll ?

**Comment by pavgra** [comment]
Cool! Then @johnSamilin will do the changes and we'll see whether anything else comes out. And as we discussed earlier, the approach, which we are targeting, is to go with PRs module by module, not with an insanely huge one.

**Comment by pavgra** [comment]
@chrisknoll , have you seen what is in the `index.js`? any suggestions for better naming?

first `data-sources` is the module name
second `data-sources` is the page name

I would suggest to wrap the refactoring of single data sources module into PR, go through it with a review and merge it

**Comment by chrisknoll** [comment]
> have you seen what is in the index.js? any suggestions for better naming?

No, I was just looking only at the project structure to see if it conveys the information about the project structure without needing to have to look inside the files to get the general idea (which is what the point of the folder-restructure is), and so I'm just giving my perspective based on just looking at the structure.

But I'll look into the files I have a question on and suggest names that reflect their purpose.  Thanks, @pavel and @johnSamilin!

**Comment by pavgra** [comment]
@chrisknoll / @johnSamilin , another suggestion from me is to build module-local permission services. E.g. permission checks of Cohort Characterization module are not required anyway outside of the module, so keeping them encapsulated will allow to keep global `AuthAPI` from growing w/o a need more and more:

![image](https://user-images.githubusercontent.com/10010071/45658397-b2baba80-babc-11e8-895a-a4f904a43436.png)

**Comment by anthonysena** [comment]
Closing due to age and it appears that most major concerned were addressed via PRs linked to this issue.
