### ISSUE TITLE
holy-war over module systems

### ISSUE THREAD

**Issue by Sigfried** [OHDSI/Atlas#654]
[moved from #633]

Is anyone is considering getting away from requirejs anytime soon?

I'm back to working on ATLAS and I want to use libraries written with ES6 imports. I think I can get stuff like that working with something like https://github.com/mikach/requirejs-babel, but if we might be moving toward ES6 module imports, there's no sense messing with temporary bridging kludges.

Has this been discussed lately?

**Comment by Sigfried** [comment]
Module paths seem pretty clear:

        import _ from 'underscore'  // imports from npm-installed package
        import myLib from './somepath/to/myLib' // explicit relative path 
        import myLib2 from 'mysrc/myLib2' // if you don't like relative paths, make symlink from node_modules

I'll take a look at stealjs

**Comment by chrisknoll** [comment]
Two points I think you missed:
1.  none of your examples include a file extension: my point being it is not defined in any specification how these should be handled, it is up to the build tool to handle it (via regex matches -> loaders or some other mechanism).  This is not a standard.
2. Your assumption that 'underscore' imports from a npm-installed package highlights my point about the 800lb gorilla.  In a browser, you don't have an NPM manager that is going to resolve those moduleIds to the correct source location on local disk or to a network location.  It's assumed that there's some builder that is at play. Wen ES6 becomes a native feature, you shouldn't need to build/transpile/resolve npm paths anymore.  But the attitude in the NPM community is that whatever solution they support, it can't impact the millions of modules that they host, so there's this deadlock about how things are going to get implemented that can work equally well on servers and bowers.  They even have this absurd notion that es6 modules should have a .mjs extension on them. So have fun rewriting all your import 'mysrc/mylib2.js' into 'mysrc/mylib2.mjs'!

But, then you have libraries like Steal.js which don't make you pick a side, they let you write modules naively in ES6 or consume AMD modules.  So I hope you really dig in and enjoy that video.

**Comment by chrisknoll** [comment]
` I think I can get stuff like that working with something like https://github.com/mikach/requirejs-babel, but if we might be moving toward ES6 module imports, there's no sense messing with temporary bridging kludges.
`

So I looked at this plugin, and what was the kludge? Anything that is going to load an ES6 module in the browser is going to have to go through a transpile step, either through a build or at runtime.  This es6 plugin has a dependency on babel so that it transpiles at runtime.  Isn't transpiling the 'kludgy' thing no matter if it's through a build tool or at runtime?

And the syntax seems simple enough:
```
// note no .mjs!
define(['es6!mysrc/myModule.js'], function(module) {
... use module here ...
}
``

**Comment by Sigfried** [comment]
About your point 1: I've been using create-react-app, but most configurations will have the same expected behavior regarding this type of module resolution: if no file extension is given and there is no path specified, the module is assumed to be npm installed and will follow instructions in that module's package.json; otherwise, the default is to add '.js' to the file name, unless there is already a file extension matched by some loader (most configurations, for instance, would include a loader for .css files).

Your point 2 is alarmist and biased and doesn't match the experience of people doing modern-day browser-based development. I'm not an expert around how all the standards are going to roll out, but npm has served as a very consistent standard for several years. Problems with porting its model from node.js to browser-based environments have developed slowly with various competing tools (browserify, bower, webpack, etc.), but they keep getting better and easier to use. I don't expect to have to rewrite my applications if and when a module loading standard finally makes it to browsers, but I do expect to have things be easier in new applications.

Where things get hairy, and they are extremely hairy now with ATLAS and require.js, is supporting old applications while wanting to use newer modules that are difficult to import in the old system. I've gotten to the point that I can put react modules into ATLAS pretty easily, but certain other packages are giving me big headaches. Specifically, mermaid.js, which doesn't have a massive community behind it and mixes ES6 and older code in ways that work for most people, but not for me trying to fit it into ATLAS with React. And this is my answer to your second post. It _seems_ simple enough and I got ES6 modules and React components working, but now I have more moving parts and I've spent 10 or 15 hours trying to get mermaid.js working without success.

**Comment by chrisknoll** [comment]
Again, I think you're missing the points I'm making:

> if no file extension is given and there is no path specified, the module is assumed to be npm installed and will follow instructions in that module's package.json; 

None of these things are specified in the ES6 standard.  You started this thread about module systems.  My points are about how the ES6 module definitions is incomplete.  You keep going on about how npm this, and package.json that, and that is NOT specified in any ES6 standard. My point was to wait until we have that standard specified so that we don't move from AMD to npm-es6transpile to native module support.

> a file extension matched by some loader (most configurations, for instance, would include a loader for .css files

Again, what loader? There is no standard loader, because there is no standard for loading!

> Your point 2 is alarmist and biased and doesn't match the experience of people doing modern-day browser-based development.

Please avoid the ad hominem attacks; I'm giving you the facts. You can read about the .mjs extension here: https://medium.com/@giltayar/native-es-modules-in-nodejs-status-and-future-directions-part-i-ee5ea3001f71.  You can read about the NPM loader module resolution algorithm here: https://nodejs.org/api/modules.html#modules_all_together.  None of this is part of an ES6 module standard.  Doing that sort of module resolution in a browser is not feasible because you wouldn't do a filesystem scan of the serverside filesystem from a browser using HTTP requests.  You're not asking about using ES6 modules, you're asking about switching our modules into NPM modules.

> I've gotten to the point that I can put react modules into ATLAS pretty easily, 

Yes, react react react react....it always seems to come back to react. But react isn't a module loader, is it?  We're not talking about how react plays (or doesn't play) nicely with other frameworks.  So, are we really talking about using ES6 module loaders or React interop?

**Comment by Sigfried** [comment]
i've apparently fallen behind on the latest javascript news. maybe ES modules really are on the cusp of being ready for prime time. i'll see if i can figure out how to use them for what i'm trying to do. 

steal.js looks pretty great from the video at https://stealjs.com/. if i can't get anywhere with the ES modules or mjs stuff, I'll experiment with steal.js. requirejs-babel is getting me nowhere.

**Comment by chrisknoll** [comment]
I think mixing module loaders is very tricky business.  I hope Steal.js has it worked out!

I think if you have modules that you'd like to write in ES6 but be consumed in Atlas, I think you should follow the approach the several other libraries (d3 and mermaid.js) has done:  create your library in your own project directory with a package.json, and use webpack/rollup/whatever to create a UMD build that can be used by Atlas, or basically any other website out there.

In the context of mermaid.js:  they have deployed their module, and you can view it here:
https://unpkg.com/mermaid@8.0.0-rc.8/

Inside this dist folder, you see that there's a mermaid.js, mermaid.min.js, and mermaid.js.map (among others). These files were built through some bunder, but has a UMD wrapper so it can be consumed by node or AMD.

For atlas, if you wanted to use this library, you just add this to the config:

```
// inside the paths config:
  'mermaidjs': 'https://unpkg.com/mermaid@8.0.0-rc.8/dist/mermaid.min'
```

then in any part of the application, you can use it:

```
// some module:
define(['knockout','mermaidjs'], function(ko,mermaidAPI) {

// use modules here
  mermaidAPI.render({...});
});
```

I'd recommend you follow the same pattern.  We do this in our visualization library (as far as bundling up a JS file and deploying it to npm so it can be loaded via CDN in unpkg).  This way you can write modules with the beloved import/export syntax, but also have it accessible to any javascript client.

**Comment by Sigfried** [comment]
Thanks for that. Sounds like a reasonable approach. I'll try it.

**Comment by anthonysena** [comment]
Closing this out due to inactivity.
