### ISSUE TITLE
Population Visualization / Attrition view interpretation

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Atlas#692]
### Expected behavior
I would expect the box the be green and say 0 criteria passed if i do not have inclusion rules defined. I understand there is probably no criterium in this case since the attrition is only on inclusion rules not on the index rule, but the current color and statement is a bit counter intuitive in my view?
### Actual behavior
Red, 1  criteria failed
### Steps to reproduce behavior
Create one with and the same without an inclusion rule

No inclusion rule:
![no-inclusion-rule](https://user-images.githubusercontent.com/7252105/40167874-6e022910-59c2-11e8-8a4b-5cfd8429f697.png)

With inclusion rule:
![inclusion-rule](https://user-images.githubusercontent.com/7252105/40167880-6ff29f70-59c2-11e8-840b-63f635874736.png)

I find it hard to explain this to new users or am I missing something here?

**Comment by chrisknoll** [comment]
Colors represent number of criteria that passed, going from dark green representing no fails (all passes) and red representing no passes (all fails).  The reason why the 'no inclusion' report shows red is that the population has no group that passes any criteria.  We could make it green, but then a green would represent that something passed (but in the case of no inclusion rules, would that be misleading?)  

So, just explaining the logic. Maybe if we just hid the report in the case there are no inclusion rules (since the report is for inclusion rules....)

**Comment by pbr6cornell** [comment]
I like the recommendation to hide the report when there are no inclusion reports.
