### ISSUE TITLE
Generate jobs should be dissociated from UI

### ISSUE THREAD

**Issue by cgreich** [OHDSI/Atlas#700]
### Expected behavior
Pressing Generate and launching a job should have no effect on UI functionality. Also, an "Abort" button is needed.

### Actual behavior
After pressing Generate and the job goes to "Pending" and the UI freezes all other activity. Or worse, it allows to doing some things but the Save button is greyed out.

### Steps to reproduce behavior
Start a whole lot of jobs, and then they stop progressing from Pending to Running.

**Comment by chrisknoll** [comment]
Thanks @pavgra.

@cgreich : while generation is happening, you can't save the cohort because that would be 'pulling the rug out from under it' while it is executing.  I don't think the UI is 'frozen' (unless you're describing another issue), rather certain elements are 'locked' while generation occurs.

Adding a cancel job button would help 'unlock' those things which are locked during generation.

**Comment by cgreich** [comment]
Yes, that's what I mean.

**Comment by anthonysena** [comment]
Closed by https://github.com/OHDSI/WebAPI/issues/430
