### ISSUE TITLE
Notifications should not be shown if user is not authenitcated

### ISSUE THREAD

**Issue by gklebanov** [OHDSI/Atlas#747]
Notifications button should not be shown if user is not authenticate. Also, if user session expires, user should be forwarded to a default login page vs. showing an empty page

**Comment by pavgra** [comment]
If use session expires, the following popup with proper notification is already shown
![image](https://user-images.githubusercontent.com/10010071/41655262-63fc218e-745a-11e8-9b2a-b3a2b5f68b46.png)

**Comment by gklebanov** [comment]
@pavgra  - I am referring to ATLAS still showing and allowing to access ATLAS Notification (bell icon) when session already expired (not the session expired notification). I cannot post it here due to some potentially confidential information on that screen shot. 

When session expired, there should not be any previous session information display - just a login page you posted above

**Comment by pavgra** [comment]
@gklebanov , that's clear, agree. In my message I responded to second part of your request:
`Also, if user session expires, user should be forwarded to a default login page vs. showing an empty page`

**Comment by fdefalco** [comment]
In the 2.7 deployment the notification icon is showing and allowing access to notifications when security is disabled and I'm unclear if this is intended.

Also the previously existing functionality where the notifications were limited to those started by the client session is no longer functioning.  

Now all jobs that are started by any user in the environment triggers a job notification to all users and a status change of the notification icon.  The list is no longer limited to jobs started by the client session but instead includes all jobs run on WebAPI.

**Comment by fdefalco** [comment]
Additionally the button that allows the clearing of notifications has been removed.

**Comment by AntonStepanof** [comment]
@fdefalco 
Currently there are 10 last notifications, without clear button.
Now user can see notifications from jobs, that user didn't start for cases:
 - when security is disabled
 - there is no author for job

Is it required some changes here? Also should be opportunity again to clear notifications?

**Comment by anthonysena** [comment]
This issue has gone in a few different directions. Let me suggest the following:

- @olga-ganina: Can you confirm if @gklebanov's original issue is fixed in 2.8 with security enabled? If so, I'd propose we close this issue.
- @fdefalco per your comments above: 
  - https://github.com/OHDSI/Atlas/issues/747#issuecomment-474934476): I believe the intention of the changes made around this feature is to remove the client-session behavior (which used localStorage) so that all notifications come from WebAPI instead. While this change was not anticipated, I'm not sure we want to further entertain changes to this functionality for 2.8. Let me know if you have any concerns with that.
  - https://github.com/OHDSI/Atlas/issues/747#issuecomment-474935472: Linking this to #539 since there are some changes aimed to address hiding completed jobs.

**Comment by anthonysena** [comment]
Closing as the initial issue reported here has been closed.
