### ISSUE TITLE
No tests

### ISSUE THREAD

**Issue by cerdman** [OHDSI/Atlas#8]
Any plans to add unit or e2e tests?

**Comment by fdefalco** [comment]
Is there something in particular you are interested in having tests for or just in general?

**Comment by pbr6cornell** [comment]
That's sounds like a terrific opportunity for a community contribution!
What do you have in mind?  Wanna pitch in and help?

**Comment by cerdman** [comment]
I will throw some unit tests into a PR in the next couple weeks... I think all components should have unit tests at the minimum to guarantee proper functionality -- IME all it takes is a version bump in a 3rd party lib like jquery or knockout and things break.

By the way - are you guys married to using knockout.js for this? Or would you ever consider something like angularjs?

**Comment by fdefalco** [comment]
I wouldn't rule out using angularjs, but what would be the motivation for the switch?

**Comment by chrisknoll** [comment]
I'll go on record saying I'm married to using knockout.

**Comment by cerdman** [comment]
@chrisknoll - How do you test for breakages when bumping to new lib version? If another OMOP component like WebAPI is changed - how do you or people using this app test for breakages? Seems like unit tests would make that a ~1 minute exercise and subjective otherwise.

@fdefalco - RE: motivation for this case for angular:
* Separation of Model, View, Controller logic - no js or other logic inside of html templates (view); reusable components; separate service factories for things like RESTful service interaction. Much more DRY.
* Data binding just works (no `ko.observable...` + template init. Just `<input ng-model='mymodel.field'/>`
* Routing is greatly simplified - parent/child views eliminates need for all those `data-bind: if page==..'` 
* Dependency injection - it uses a module based system which forces solid organizational principles.
* Built for testing from the ground up - again, it just works right out of the box.

**Comment by fdefalco** [comment]
That would be great.  There was some discussion early on about using angular but there had already been some investment in knockout.  One of our applications (OHDSI/Heracles) is in fact angular based so there is some precedent for its use in the OHDSI community.  

I will happily take a look at your mini-port to angular and see how things look.  Thanks for your interest.

**Comment by chrisknoll** [comment]
That being said, when we looked at components from CIRCE, HERMES, and ACHILLES, the question was asked if we could move them into HERACLES. Because they were based on different frameworks, it wasn't a straight move (for example, a knockout data binding for a line chart doesn't just drop into an angular view).  

I agree that we need a testing framework to help ensure code still runs after updates (such as d3, jquery, jqueryui, knockout, bootstrap, etc).  I do not agree that moving to angular will solve this problem.  We can find a testing framework that sits on top of knockout, and I'm sure the testing considerations that apply to an angular based app will apply equally to a knockout based app.  I'm definitely interested in seeing a testing strategy in Angular to get the perspective, but I feel the best use of energy would be to figure out how to apply a testing framework on the code we already have.
