### ISSUE TITLE
Cannot navigate directly to concept

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#806]
### Expected behavior
Navigate directly to a concept using the concept URL: http://localhost/atlas/#/concept/4294416 and the concept's information is properly displayed

### Actual behavior

Navigating directly to a concept using the code currently on master errors with 

`GET: http://localhost/atlas/undefinedconcept/4294416 404 (Not Found)`

And the page does not load

### Steps to reproduce behavior

See above. As a note, I'm doing this without security enabled. I've traced through the code and have determined that part of the problem is that the sharedState (/components/atlas-state.js) has not been initialized at the time when js/pages/concept-sets/routes.js is loaded. This is the reason for the "undefined" portion of the offending REST call above. 

Previously, routes were loaded after the sharedState initialization which prevented this type of an issue. With the refactoring, it appears that this loading sequence is compromised thus resulting in the above error.

Tagging @pavgra, @wivern and @johnSamilin for input.

**Comment by chrisknoll** [comment]
I've seen this, I think it's related for some async startup of some of the components.  We should have a place in app.js (or main.js) where we wait for all app-startup operations to finish and then we start processing routes...but I think routes are being handled prior to the main application init completing.

**Comment by johnSamilin** [comment]
First of all, the right link is `http://localhost/atlas/#/concept/4294416/details`, `http://localhost/atlas/#/concept/4294416` will redirect to a search page.

The problem here is that the application won't know anything about available sources until you login. Thus, it also won't know what `vocabularyUrl` is. So that is not the concequences of the refactoring process. But the point is true - we definately should have a single place where all the data synchronization is done. And the app's startup process should wait for it to complete.

**Comment by anthonysena** [comment]
Thanks @johnSamilin. A few points:

In previous versions, navigating to the URL `http://localhost/atlas/#/concept/4294416` would load the `http://localhost/atlas/#/concept/4294416/details` and I think that is appropriate. Furthermore, the problem I noted is happening with security disabled - sorry if that was unclear.

I think @chrisknoll's suggestion of having all of the initialization done before loading routes is correct and is consistent with how this was working in V2.4.0. Please let me know if you need any further information or would like any help in reviewing the changes. Thanks!

**Comment by chrisknoll** [comment]
I used to see this specific error when going directly to a cohort definition (ie: ```atlas/#/cohortDefinition/{id}```) but I'm not gettign that anymore on master.  I'm not sure if the fix for when it was happening was handled as part of the cohort definition route, or something at a higher level, but yes, to @anthonysena's point: at one point there was a collection of promises that app.js (or main.js) waited for to complete, and once finished, it let the rest of the application go (ie: respond to routes).  I think with the introduction of security, I think other things had to be also checked and some of the 'wait for app to be ready' logic was lost.
