### ISSUE TITLE
Improve terminology in Cohort Editor

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/Atlas#824]
@cgreich  would like to revisit some of the terminology used in the cohort editor with respect to the use of the term 'criteria' in the editor.

In addition to the use of criteria, the other elements of the UI editor and how 'intial events' and 'qualifiying criteria' could be updated to be more clear.

**Comment by chrisknoll** [comment]
### The use of criteria vs. criterion

Continuing the discussion from OHDSI/WebAPI#495:

@cgreich  writes:

> @chrisknoll: Criterion. ON. Can we fix that in the next release? It's also Nation, not Natia.

Aside from plural of 'nation' being 'nations', the thread brought up some points about where and when you'd use criteria vs. criterion:

> So, in the above screen I would change:
> Add criterion to group (you are adding one at a time)
> Add criterion attribute (an attribute is something belonging to one criterion)
> Delete criterion (you are deleting just one)
> With the following event criterion
> 
> Criteria (blue button) - makes sense
> Having all of the following criteria - makes sense
> 
> Ok?
> 

Which I responded with:

> > Add criterion to group (you are adding one at a time)
> 
> No, you are adding a group of criteria . I think this is the proper use:  you say 'a group of children' not 'a group of child'.  It stays as is.
> 
> > Add criterion attribute (an attribute is something belonging to one criterion)
> 
> No. While 'attribute' is not the term I would use for this, you are still adding to the criteria. You are 
> adding to the children, not adding to the child. And you are not adding a child attribute, you are adding attribute to the children.
> 
> > Delete criterion (you are deleting just one)
> 
> No, you may be deleting multiple criterion (the age criterion, the duration criterion, etc).  You are deleting _criteria_.
> 
> > With the following event criterion
> 
> No. Same as above: it would read 'With the following criteria:  'Age > 18, starting after 1/1/2011, With duration of X'. These are the _criteria_.  Same thing as 'These are the children'.
> 
> Your impression that these things are singular is at issue here.  But the reality is that we're talking in the plural. So, if you understand that you understand both the use of the tool and also the use of the terminology.
> 

The one element of the argument I can agree with @cgreich is when you add a criterion to one of the criteria groups, the button says 'add criteria attribute'.  In that case, you are adding an atomic element to a criteria (whether it be age, gender, year of occurrence, etc, each of these represent a singular element of criteria that is added to the group).  We could say 'Add criterion' or 'add to criteria'. 

In all the other cases, I stand by that it is important to understand in the editor that when you talk about 'condition criteria', you are stating more than one criterion must be true for that event to be selected.

**Comment by chrisknoll** [comment]
### Initial Event Cohort
Problem:  the event pool selected by the initial criteria is not actually a 'cohort':  A person can have multiple events that have overlapping periods numerous times in the pool.  Further, it's hard to justify 'defining a cohort' by starting with a cohort.

Proposed Terminology:
- Primary Event Criteria
- Initial Event Pool
- Primary Event Pool

Information Description:

> The criteria that selects a pool of events that will be used to derive cohort episodes belonging to the cohort.

**Comment by pbr6cornell** [comment]
I understand the confusion for using the word 'cohort' in the title of the
first section on the cohort definition editor.

Why not simply revise it to 'Initial events', which defines the set of
observations which can potentially qualify a person to be part of a cohort
for a duration of time.  We then apply 'inclusion criteria' (plural because
it is a set of zero or more entities) to these initial events to determine
which are the 'qualifying events'.  For each 'qualifying event', we apply
'exit criteria' to determine when an episode would end, if the qualifying
event was in fact a valid entry.  Then, we apply era-fication and date
censoring logic to determine the final cohort start and cohort end dates.

In this language, I am simply removing the term 'cohort' from the
prerequisite steps, as I agree that can be confusing.

If we are looking to be more specific in our language, we could use
'Initial entry events' and 'qualifying entry events', though I'm not sure
how much that really clarifies things.

I do not support the use of the term 'pool', as that is neither an
epidemiologic term nor a standard definition of the word in other
contexts.  I also would recommend against using the word 'primary', unless
we find ourselves in some circumstance where we have a single entity that
is either 'of chief importance' or 'earliest in time' (the two webster
definitions for the term), and I don't think either apply generically in
our current definition context.

**Comment by chrisknoll** [comment]
'Initial events' works for me.  'Prime' and 'Initial' are synonymous in the sense that 'nothing comes before'.  ie: a prime number: there are no prior factors of a prime number'. So the thought process of thinking of 'primary events' are those events that begin the cohort definition process. But, 'initial events' works that way too.

Re: pool: not all terms that we'll use in the cohort definition UI 'help context' (or in the tutorial for that matter) will be solely epidemiological.   The term 'pool' is just a conceptual construct used to bring to mind the idea that there is a group of events that are 'brought together' or 'pooled' by the initial event criteria.  We could say 'set' or 'group' when referring to this collection.  What is the epidemiological term for 'collection''?

**Comment by pbr6cornell** [comment]
If we use the phrase 'initial events',  then I do not see the need for
adding another term like 'pool'/'set'/'group'/'collection'.

You apply 'initial event criteria' to identify your 'initial events'.

You apply 'inclusion criteria' to the 'initial events' to identify the
'qualifying events'.

You apply 'exit criteria' to the 'qualifying events' to  set a end date for
each qualifying event.




If you think 'prime' and 'initial' are synonymous, then we may have
confusion in the use of the term 'initial', since it needn't necessarily be
'nothing comes before' (like if you select all events).   We could consider
'candidate entry events'.

**Comment by chrisknoll** [comment]
I meant 'nothing comes before' as in that is the starting point in the process, and you're getting my point about using the terminology of 'initial' may have some connotation about a temporal ordering of those events which could lead to confusion instead of 'this is the starting point of the cohort definition.

If we wanted to draw a picture of the process it would be:

```
Initial/Primary Events -> Initial Event Criteria -> Additional Criteria (for impact analysis) -> Exit Strategy -> Censoring Events -> Censor Window -> Episode Construction
```

So, the 'primary' terminology here is just ... nothing comes before selecting those events, making them primary.  Using 'initial' would be 'You begin by selecting your initial events'....I can go with either approach, but I do want to avoid confusing terminology.  What would be the least confusing?

**Comment by pbr6cornell** [comment]
I think 'exit criteria' remains valid terminology.  Per Webster, 'criteria'
are " a standard on which a judgment or decision may be based ".  In this
case, the judgement/decision we are making is what end date to specify for
a 'qualifying entry event', and the standard is based on various options,
including a fixed duration relative to the qualifying entry event, a
duration based on continuous exposure to a drug, the end of observation
period, or the occurrence of a 'censoring exit event'.

**Comment by chrisknoll** [comment]
yes, you are correct about the Websters definition, but it's not a consistent term used when selecting records for initial events/qualifying criteria vs. how the exit dates should be constructed.  I would like a different terminology here because they operate in completely different ways.

**Comment by pbr6cornell** [comment]
Personally, I find 'primary' more confusing because it is commonly used to
be 'one' item.

Based on the words bandied about, my process would look like:

Initial events -> Inclusion Criteria -> Qualifying events -> Exit criteria
-> Episode construction


While the ATLAS UI currently provides 2 opportunities to have 'inclusion
criteria', that is provided for the utility of selecting which criteria
should be evaluated.  The current UI separates that out, but could have
just as well had been organized as one section, partitioned by which are
executed as part of the initial events and which are evaluated separately.
(recognizing there is a temporal ordering in how these criteria get
executed).

'Exit criteria' should include the specification of candidate end date and
the option to consider censoring events, or to censor the dates.  (there is
the awkwardness of left-censoring the cohort start date, which isn't
obvious where that needs to be).

'Episode construction', that feels like we'd like a better term for that,
but the notion there is you have a set of 'qualifying event start date/end
date pairs' and we era-fy them to entities that actually satisfy our
definition of a cohort record, indicating that a person satisfies one of
more criteria for a duration of time.

**Comment by chrisknoll** [comment]
How about 'Exit Specification' in stead of 'Exit Criteria'?

**Comment by chrisknoll** [comment]
Here's a set of changes I am proposing:

![image](https://user-images.githubusercontent.com/6818777/45112910-fd305480-b116-11e8-9e3d-ea1e5f1baddd.png)

1. Rename Initial Event Cohort -> Initial Events
2. Rename Additional Qualifying Inclusion Criteria -> Inclusion Criteria
3. Remove 'Criteria' from 'Add...' dropdowns, remove 'Criteria' from Add attribute dropdowns.
4. Combine Cohort Exit Criteria and Censoring Events into single group: Cohort Exit.
  -- 2 sections:  Event Persistence (see 5) and censoring events
5. Change display of End Date choices from hyperlinks to dropdown options:
Event will persist until: [dropdown]
  - end of continuous observation (default)
  - fixed period relative to initial event
  - end of continuous drug exposure

6. Combine Cohort Collapse Strategy and Cohort Censor window into 1 group: Cohort Eras
- allowable era gap
- left censor cohort start dates to ...
- right censor cohort end dates to ...

Also, changing the wording of 'Limit events ...' to 'Limit qualifying Events' and 'Limit initial events...'

**Comment by chrisknoll** [comment]
Here is the latest mockup based on the above proposed changes:
![image](https://user-images.githubusercontent.com/6818777/45257205-5d6e0300-b370-11e8-9dc7-bbcaff01ff30.png)

This layout flows through the cohort definition process:
Initial Events: the set of events which may qualify a person for inclusion in the cohort
Inclusion Criteria: apply rules to those events to keep them in the cohort
Cohort Exit: Specify how long events should persist, and allow users to specify different set of events to censor the event.
Cohrot Eras: With the remaining qualified events, construct eras with the specified allowable gap, and optionally specify left and right trimming of eras.

**Comment by gowthamrao** [comment]
@chrisknoll this looks great!

**Comment by cgreich** [comment]
@chrisknoll:

Love it.

Couple comments (some of them may already been discussed)

- Why don't we use the word "index" instead of "initial"? That's what people are used to. It should also indicate that the start date of the initial/indexing event will determine the start date of the cohort.
- The "initial" also adds to confusion because folks assume it be the first, but in fact the inclusion ones might (and often do) come earlier.
- There is no device
- There is still "Select a inclusion criteria". Either "Select inclusion criteria" or (better) "Select an inclusion criterion" :)
- Why is the button "+Add Initial Event" blue and on the right and uses a plus and the word "Add", and "New inclusion criteria" green on the left and starts with "New"? Why not a blue "+Add inclusion criterion on the right? On the bottom, you have yet another style: "add trimming options..." is a hyperlink. I would harmonize these all.
- I would drop the word "Please". We don't have time or screen real estate for niceties.
- I would harmonize the capitalization on all buttons and headings. I'd go for only first letter capital, and the rest lower case. "Enter a cohort definition description here", "Initial events", "Add initial event", "Restrict initial event", "Inclusion criteria"
- The "with continuous observation of at least.." confused people, as you can see on the Forum/Github. We need to make it clear what the purpose of it is (making sure there is washout period, making sure there is follow-up time, but only for the purpose of the cohort). They still try to enforce time at risk here.

**Comment by chrisknoll** [comment]
@cgreich 

> Why don't we use the word "index" instead of "initial"? That's what people are used to. It should also indicate that the start date of the initial/indexing event will determine the start date of the cohort.

See the above discussion on the term 'Initial' vs. 'Primary'.  I'm sure @pbr6cornell  can point to examples where referring to these events as 'index' is not appropriate.  I think some of the problem with your interpretation of these words is that you are making some assumptions about what you think these things are vs. what they actually _are_.  So, The 'Initial Events' are those events that are the starting point to the cohort construction process. They are not 'Initial' because of some sort of temporal ordering of events. They are 'Initial' because this is the first step in the process.  There is no event selection before the 'initial event selection'...If you have a term that can signify 'A selection of a group of things', please make it.  I don't think 'Index' is the correct term for that.  I suggested 'Primary' for this in a prior thread (you should go back and read those comments carefully) but the counterpoint was that was indicating some hierarchy of status (the primary reason)...but in the context of 'starting group' i thought it fit. But we went with 'Initial Events'.

> The "initial" also adds to confusion because folks assume it be the first, but in fact the inclusion ones might (and often do) come earlier.

In the process of event selection, in your mind, what are the events that come before the 'Initial Events'?

> There is no device

I'd like to ask you be more specific in your feedback.  "There is no device'?  The 'Add Device Exposure' is selecting records form the 'Device Exposure' table...

> There is still "Select a inclusion criteria to edit". Either "Select inclusion criteria" or (better) "Select an inclusion criterion" :) Or, if you really need to torture me, at least "Select an inclusion criteria".

I'll fix the typo of 'a' to 'an'.  If the button is 'add inclusion crtieria' then it certainly follows to say 'select an inclusion criteria to edit'.

> It's actually not clear why that sentence is there to begin with. Before you have any inclusion criteria you cannot select. Instead you can add. And when you have - use standard conventions for hyperlinking or highlighting.

I'll remove the message entirely.

> Below it says "Limit qualifying events to..". What's now a qualifying event? (Probably left over).

It lets you limit the remaining (after inclusion criteria are applied) to a single event per person.    You can limit the Initial events to the very first or last event, or you can let all the Initial events through to the Inclusion Criteria and then limit the Initial Events that pass the Inclusion Criteria (aka: qualifying events).

I definitely do not expect anyone to just look at a few words on the UI and have a complete, initiate understanding of what the tool is doing.  But, I think it's fair to say that once you get the idea of the 'Initial Events' vs. the 'Qualifying Events' you don't need to have verbose text to describe it.  Just like you have your instruments in your car you drive, you have a little 'E' and a little 'F' next to a gague that looks like a little miniature fuel pump; you don't need text next to the 'E' saying 'E represents the level of fuel in your gas system when their is no longer gas in the system, known as 'empty''  or 'F' saying 'F represents the level of fuel where your gas system can not take any more gas, known as 'full'.  You get in your car, you know what E and F means for your gas, and you don't need a verbose label on it to remember.

> Why is the button "+Add Initial Event" blue and on the right and uses a plus and the word "Add", and "New inclusion criteria" green on the left and starts with "New"? Why not a blue "+Add inclusion criterion on the right? On the bottom, you have yet another style: "add trimming options..." is a hyperlink. I would harmonize these all.

We could have one color be used by those things that are drop-down selectors (so the Add ... buttons are dropdowns) while the other buttons (New Inclusion Rule) is not a dropdown, just a button that is easy to find to click that performs an action.  The only violation to this rule is the 'concept set selector' is a green drop-down, which we could change to blue. 

The hyper-link selection at the bottom is in line in other elements of the UI where you have a required element of data and optional secondary choices.  So different use-cases have different behaviors, and doesn't lend itself to 'harmonizing'.

> I would drop the word "Please". We don't have time or screen real estate for niceties.

Per prior response, I'll remove the message, but the net-gain will be zero for screen real estate.

> I would harmonize the capitalization on all buttons and headings. I'd go for only first letter capital, and the rest lower case. "Enter a cohort definition description here", "Initial events", "Add initial event", "Restrict initial event", "Inclusion criteria"

I'd like to wait for other input on this, but the section headings are 'titles' and I think they should follow the convention of things that are titled, like a title of a book.  I'd like to hear other opinion on how the buttons should be treated.

> The "with continuous observation of at least.." confused people, as you can see on the Forum/Github. We need to make it clear what the purpose of it is (making sure there is washout period, making sure there is follow-up time, but only for the purpose of the cohort). They still try to enforce time at risk here.

This is just a term that anyone with CDM proficiency should understand (ie: they understand what the OBSERVATION_PERIOD table is used for).  It would be incorrect to call this a 'washout' since that is a very specific term for 'new user cohort design' that would not be applicable for cohorts where you are trying to create a predictive model, and the people in the cohort should have a certain amount of prior observation, and possibly a certain amount of post observation.  'Continuous observation' isn't something specific to cohort definitions, it's core to the Common Data Model.

**Comment by chrisknoll** [comment]
Updates to mock-up from @cgreich  feedback:
![image](https://user-images.githubusercontent.com/6818777/45260001-932ede00-b3a8-11e8-9ea3-9f76b8daa561.png)

Removed 'Please select' from Inclusion Criteria.
Made concept set selector a blue drop-down to match the other drop-down (not a terminology issue, but we want to keep Christian happy)

**Comment by hripcsa** [comment]
FYI, when I explain Atlas to someone, I ignore the name "initial" and call it the "triggering" event that "anchors" the cohort in time. The rest are inclusion criteria (just as named).

**Comment by hripcsa** [comment]
Come to think of it, the inclusion criteria are actually just negated exclusion criteria. Usually, in clinical trials, "inclusion" tells you who gets pulled in. But the inclusion criteria here pull no one in; only the initial event criteria pull people in. Our inclusion criteria just throw out (exclude) those who don't meet them. So in explaining current Atlas, I would tell someone that the top of the first box defines the population of interest and anchors each patient to one or more points in time. The bottom of the first box adds criteria for keeping and removing people from the population. The second box is similar, but when you generate it, you can see the breakdown under Generation.

**Comment by chrisknoll** [comment]
Good points @hripcsa .

When we first were thinking about how these things should work, we did look to clinical trial protocols to get ideas. One funny thing that we'd see is something like:

```
Inclusion Rules:
  Has Hypertention

Exclusion Rules
  Not pregnant
```

So to take the exclusion to me the inverse of the inclusion: excluding 'not pregnant' means 'you must be pregnant'!  of course, we know what they really mean, but we made the conscious decision to always speak in terms of the positive:  you must have at least 1 hypertention...you must have exactly 0 of pregnancy.

That's why I'd take what you said a bit differently:

> Our inclusion criteria just throw out (exclude) those who don't meet them
 
To phrase this using the positive:  

> Our inclusion criteria just keep those who meet them


Sometimes the double negative bites you, so we remove the double-negatives all together.

**Comment by hripcsa** [comment]
(I definitely agree not to call it exclusion. I just meant that inclusion may also be confusing.)

**Comment by pbr6cornell** [comment]
Team:

Just to level set of where I think @chrisknoll was initially requesting feedback:  at this time, we are looking for feedback on the language (text) on the existing UI, so that we can make it more clear in areas where the community has expressed confusion, and so that we can have have a common terminology about cohort definitions that can be used during upcoming tutorials that can be consistent with the ATLAS UI.    There may be a good reason to consider a larger-scale UX refactoring once we get additional community feedback on the existing tool (from the upcoming tutorial and otherwise), but I do not expect that to take place before the 2018 Symposium and certainly not before the ATLAS 2.6 release that will precede the 2018 Symposium.

To the topics that seem to be points of conversation on this thread:


#1: Redefining the phrase 'initial events':

'Initial events' is the current language in the tool, though it sounds from the feedback that there is some confusion with the use of this term.  I agree with @chrisknoll that 'index events' is rather loaded, as many people have diverse ideas of what index does or should mean (and the term 'index' itself has different meanings with different study designs, think the index of a comparative cohort design vs. the index of a case-control design vs. the various 'index-less' risk windows in a self-controlled case series).

How about revising 'initial events' to 'entry events'?

It can be described as part of the following process.  A cohort is the set of persons satisfying one or more inclusion criteria for a duration of time.  We implement this cohort definition through a four-step process:  Entry event -> Inclusion criteria -> Cohort exit -> Cohort era

A person is eligible to enter a cohort at each 'entry event', reflecting a timestamped observation which .  The person will only remain in the cohort if the 'event entry' satisfies all 'inclusion criteria'.  The remaining 'entry events' need to have a corresponding exit date, so we determine the 'cohort exit' based on the earliest of some defined duration following entry or some censoring event.  Finally, we build 'cohort eras' from all entry-exit pairs to ensure that each person has one or more non-overlapping periods of time when they belong to the cohort.  



#2:  Limiting events:

I agree that 'limiting qualifying events' can be confusing in an abstract sense (and yet, if you sit down to write the code to make any cohort yourself, you realize very quickly that you have to specify a sequential precedence for the operations you perform, and at each step, you have to decide, 'do i want this operation to perform on all records or only one record per person?'.  Currently the advantage of the ATLAS UI is that it provides 3 different places for this decision to be made, because that offers a lot of flexibility......and the disadvantage of the ATLAS UI is that it provides 3 different places for this decision to be made, because that offers a lot of confusing flexibility.

Currently, the UI says 'limit initial events' in the top section, and 'limit qualifying events' in the middle section.  Since we may be getting rid of the term 'initial event' and we have already removed the word 'qualifying',  I would recommend we change all of these statements to: 'limit events to:  <all events/first event> per person'. 


#3:  Case of text:

I don't feel strongly on this topic, but based on the discussion, I suppose I'd vote for 'Sentence case' over 'Title Case'.   I agree that it would be preferable to be consistent, unless there was some purpose for being inconsistent.

**Comment by anthonysena** [comment]
Linking to #947 and tagging @chrisknoll - a lot of good ideas here and just wanted to confirm before closing.
