### ISSUE TITLE
Security / User Access

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Atlas#86]

**Comment by t-abdul-basser** [comment]
Related issues:

Implement authentication (LDAP/AD) (issue #148)
Implement authentication (GitHub) (issue #149)
Add access control for cohort deletion 
Log authentication
Modify logs for cohort creation to include user
Modify logs for job creation to include user

**Comment by chrisknoll** [comment]
I would like to voice that before we add the features to Atlas/WebAPI that would potentially storing sensitive user information, that we are absolutely sure we have any sql injection attack vector locked down so that we do not expose any data that is not supposed to be exposed to users.

Just saw this video today, and it explains how they work (which I'm sure most of us are familiar) what one technique that was especially surprising was the user of injecting a UNION clause into a select (such as in a search function) such that the UNION could be used to read any table in the schema.  This is very important for us, being open source, the malicious user would not have to guess what tables exist in the DB, since it's all open source.

Here's the video if you are interested:
https://www.youtube.com/watch?v=ciNHn38EyRc

-Chris

**Comment by t-abdul-basser** [comment]
Thank @chrisknoll. I agree fully. 

Perhap we should set up some regular security-focused code reviews and consider scripting some SQL injection security tests.

**Comment by mark-velez** [comment]
@pbr6cornell @chrisknoll @fdefalco you might notice my... reservations about implementing security, but Columbia has a somewhat immediate need for authentication; and if we *are* to hack something together, I figure we might as well try to make something more generally useful. I created a [WebAPI issue](https://github.com/OHDSI/WebAPI/issues/109) where I think the crux of this conversation is more suitable. I propose we limit this thread to front-end (Atlas) concerns.

**Comment by malcolmm83** [comment]
Will the security features include role-based access to OMOP data sources?  Is there a concept of mult-tenant in the data tier?

**Comment by fdefalco** [comment]
If by multi-tenant you mean the possibility of housing more than one person-level data set in OMOP CDM format then the answer is yes.  We have the setup in our existing environment today where we have  at least a dozen different data sources.

The specifications for the security implementation will provide for the ability to restrict access not only to features (such as generating a cohort, or deleting a concept set) but also to access to features on a particular data source.  For example a user might have permissions to create a new cohort definition within the OHDSI repository but only generate it on a data source which they have adequate permissions to use.

**Comment by malcolmm83** [comment]
I see that the WebAPI shiro branch hasn't been updated since last October.  Can I see the work in progress in GitHub?  Same question for the UI side.

**Comment by fdefalco** [comment]
The security work is being done in partnership with EMIF and is in a fork outside the OHDSI repository.  We should be able to release some work in progress just after the symposium.  The security implementation will not be introduced until after the OHDSI symposium (Sept 23-24)

**Comment by malcolmm83** [comment]
Do you know if OpenID Connect will be supported?  Looks like Shiro has support, so shouldn't be too bad.
