### ISSUE TITLE
Left-hand menu bar resolution

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Atlas#878]
### Expected behavior
The menu bar on the far left will adjust with computer screen's resolution

### Actual behavior
Menu bar adjusts, but not fully enough to reach all items

![image](https://user-images.githubusercontent.com/12911960/44728059-83aabd80-aaa9-11e8-9cb7-97e1aab2e46c.png)

### Steps to reproduce behavior
View ATLAS on low-resolution screen

**Comment by pbr6cornell** [comment]
This still appears to be a problem, so issue should be reopened.

### Expected behavior

Zooming in on ATLAS will not result in functions on left-hand bar being inaccessible

### Actual behavior

![image](https://user-images.githubusercontent.com/731930/52065506-a489aa00-2544-11e9-8fd9-e3caa16f681d.png)



### Steps to reproduce behavior

Google Chrome -> Zoom In (screenshot shows at 150% on my laptop screen....Estimation and Prediction features are not available for selection)

**Comment by chrisknoll** [comment]
The original fix was to adjust the size of the fonts based on the size of the window, but we can see that there is a case where it doesn't matter what the size of the window is, the content will always be obscured.  

Therefore, I believe we should apply a `scroll-y` style on the left nav container to scroll as needed.   Additionally we could remove the 'powered by' box on the left since it takes up a large amount of space, at least we could minimize the footprint.
