### ISSUE TITLE
Regarding WebAPI Deployment in Tomcat

### ISSUE THREAD

**Issue by umesh-clinakos** [OHDSI/Atlas#895]
### Expected behavior
It should deploy the WebAPI In Tomcat Container
### Actual behavior
While doing the deployment its is giving following error.
FAIL - Application at context path /WebAPI could not be started
FAIL - Encountered exception org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/WebAPI]]
### Steps to reproduce behavior
Deploy the war file through tomcat appliccation manager.

**Comment by chrisknoll** [comment]
We'd need more information from your logs, but based on your other issue OHDSI/WebAPI#578, you are trying to run this on MySQL which is not supported.

Although the error is reported in Atlas, the underlying issue is with WebAPI, so you only need to open up one issue on that. I'll close this one (since the issue you are having is with WebAPI) and you can close the other issue if the information there addresses your issue.
