### ISSUE TITLE
Duplicate records in Data Source Drug Report

### ISSUE THREAD

**Issue by aostropolets** [OHDSI/Atlas#913]
### Expected behavior
Drug prevalence report in data source reports will have one row per a unique concept_id.

### Actual behavior
For some of the concepts full duplicates (e.g. the same concept_id,concept_name, prevalence, counts) exist.
Example:
40231925  Acetaminophen 325 MG / Oxycodone Hydrochloride 5 MG Oral Tablet

Atlas v 2.4.0, 2.4.3

**Comment by pavgra** [comment]
![image](https://user-images.githubusercontent.com/10010071/45724778-ad757280-bb85-11e8-93f2-1ab417d939cd.png)

**Comment by pbr6cornell** [comment]
I think this is likely happening, because drugs are mapped up into the ATC
hierarchy, and this drug may be mapped to multiple locations.  If you open
the other hidden columns, you'll see it.

**Comment by pavgra** [comment]
@pbr6cornell , anyway, the difference between rows should be visible on initial screen

**Comment by pbr6cornell** [comment]
I may have made an inappropriate choice when I built the hierarchy query to
allow for a one-to-many relationship.  If we want to force concepts to have
a one-to-one relationship with only one path through the hierarchy, then
this wouldn't occur.  I'm open to whatever approach the community feels is
most appropriate.

**Comment by aostropolets** [comment]
@pbr6cornell where are those hidden columns? They hide too well :)
And then I'm not sure what you're talking about. One drug to many ATC-s is one problem (which will be fixed soon I believe), the multi-way hierarchy is another. I've somehow found that the latter annoys me as well, so we might need to discuss it indeed.

**Comment by anthonysena** [comment]
Related to OHDSI/WebAPI#347

**Comment by fdefalco** [comment]
This isn't an ATLAS bug, will be resolved within WebAPI.

**Comment by pbr6cornell** [comment]
I am still observing this same problem, that we closed as resolved.

![image](https://user-images.githubusercontent.com/731930/58270409-bee7cd80-7d57-11e9-876a-e84ec603d94e.png)

**Comment by anthonysena** [comment]
The root of the issue here is the way that the concept_hierarchy table is constructed as detailed in the [init_concept_hierarchy.sql](https://github.com/OHDSI/WebAPI/blob/master/src/main/resources/ddl/results/init_concept_hierarchy.sql#L77) query in WebAPI. In that query, there is the rollup of each drug to the ATC hierarchy which can sometimes lead to different hierarchy paths which then appears as duplicates in ATLAS. 

To take the example from the screenshot above, here is an excerpt of the return value returned from  `/WebAPI/cdmresults/<source_key>/drug` for concept_id == 19080128

```
{
	"conceptId": 19080128,
	"conceptPath": "CARDIOVASCULAR SYSTEM||AGENTS ACTING ON THE RENIN-ANGIOTENSIN SYSTEM||ACE inhibitors, plain||Lisinopril||Lisinopril 10 MG Oral Tablet",
	"numPersons": 2200303,
	"percentPersons": 0.02564,
	"recordsPerPerson": 8.82079
}, {
	"conceptId": 19080128,
	"conceptPath": "NA||NA||NA||Lisinopril||Lisinopril 10 MG Oral Tablet",
	"numPersons": 2200303,
	"percentPersons": 0.02564,
	"recordsPerPerson": 8.82079
}
```

As noted by the `conceptPath` property, the ATC rollup for this particular drug results in 2 different paths and thereby results in a duplicated display to reflect these paths. There are a few ideas that come to mind:

- Remove the hierarchy portion of the returned value from WebAPI to eliminate duplicates in the table display (for drug the hierarchy is not part of the table display).
- Collapse these hierarchy entries into a single item inside of ATLAS and remove the NA values. If there is > 1 hierarchy entry, we can then make a computed column to show the hierarchy. For example:

1. CARDIOVASCULAR SYSTEM -> AGENTS ACTING ON THE RENIN-ANGIOTENSIN SYSTEM -> ACE inhibitors, plain
2. <Another ATC 1> -> <A different ATC 3> -> <A different ATC 5>

@pbr6cornell let me know what you'd prefer to see given this information. Thanks!

**Comment by anthonysena** [comment]
From discussion with @pbr6cornell, let's plan to remove the hierarchy portion from the table display.
