### ISSUE TITLE
Fix Nested criteria descriptions

### ISSUE THREAD

**Issue by eldarallakhverdiiev** [OHDSI/Atlas#954]
### Expected behavior
Description of Nested criteria in the pop-up menu reflects chose of criteria domain
### Actual behavior
It says 'Apply criteria using the **condition occurrence** ..."  without reference to criteria domain

**Comment by pbr6cornell** [comment]
I don't understand the issue here, but if documentation around nested criteria is insufficient, then we should try to improve that in ATLAS 2.8.

**Comment by eldarallakhverdiiev** [comment]
@pbr6cornell 
Please see the image below. 
I used Device exposure as initial event, but short attribute description mentions condition occurrence.
![nested_criteria_wrong_description](https://user-images.githubusercontent.com/25959256/61180171-593df200-a5e0-11e9-9548-c6a95954af32.PNG)

**Comment by chrisknoll** [comment]
Right, that's a typo, should be more generic.  I'm wondering if it's possible to paramaterize it so that the menu item indicates the criteria type of the containing criteria...then it can say 'condition occurrence' for condition occurrence, or 'device exposure' for device, etc.

The simplest fix would be to just make it generic.
