### ISSUE TITLE
Characterization generate button behavior

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Atlas#968]
### Actual behavior
The generate button on the characterization execution tab allows generation while generation is in progress.  Sometimes the button is animated and says 'Generating' however sometimes it appears as the default Generate > label even when a generation for that data source is in progress.  In either state you can click on it to initiate another generation.  

### Expected behavior
Button consistently shows Generating or Generate label depending on state.

I'm not sure what the intended behavior is here but I think starting a new generation on the same data source should be blocked while an existing generation is running.

![image](https://user-images.githubusercontent.com/6586384/46485578-ecccd180-c7c9-11e8-946f-0c43658f1d05.png)

**Comment by chrisknoll** [comment]
We take snapshots of each generation design, so it is possible to save one design, generate, make a change and then generate again with the new design, all while the old design is running (the intermediate results are stored in generation-local tables).  

However, if the design hasn't changed, we should prompt that no changes have been made since last execution.
