### ISSUE TITLE
Deleting additional filters doesn't update code

### ISSUE THREAD

**Issue by jswerdel** [OHDSI/Atlas#97]
When a cohort is created with additional filters, after deleting these filters they are still in the code (both sql and json).  Must also click the "delete additional filters" but to finalize the deletion

**Comment by chrisknoll** [comment]
Not seeing this:  to reproduce I did the following:

1. Opened up an existing cohort definition (actually a copy of one that had additional criteria)
2. Removed all additional criteria. The JSON reflected the changes (although the 'AdditionalCriteria' group still exists as an empty group, so that you can add criteria again)
3. Saved and reloaded, changes persisted.
4. Clicked remove additional criteira button, JSON reflected the change.

This seems to work for me. Can you add steps to reproduce and the expected results and actual results?

**Comment by jswerdel** [comment]
I think the problem occurs when you start with a new cohort, add a filter, delete the filter, and save the new cohort.  The additional filter code is still in json and sql.

**Comment by jswerdel** [comment]
I was confusing loaded concept sets (which persist in the code) with what was going to get used in generating the cohort.
